// Generated by scripts/build-tokens.mjs from design/tokens.json. Do not edit by hand.

export const COLOR = {
  "brand": {
    "50": "#e8f5f0",
    "100": "#c6e8db",
    "300": "#5cc9a7",
    "500": "#16b88c",
    "600": "#0b7d5e",
    "700": "#096b50",
    "800": "#064e3b"
  },
  "blue": {
    "50": "#eff6ff",
    "100": "#dbeafe",
    "300": "#93c5fd",
    "500": "#3b82f6",
    "600": "#2563eb",
    "700": "#1d4ed8",
    "800": "#1e40af"
  },
  "cyan": {
    "50": "#ecfeff",
    "100": "#cffafe",
    "300": "#67e8f9",
    "500": "#06b6d4",
    "600": "#0891b2",
    "700": "#0e7490",
    "800": "#155e75"
  },
  "violet": {
    "50": "#f5f3ff",
    "100": "#ede9fe",
    "300": "#c4b5fd",
    "500": "#8b5cf6",
    "600": "#7c3aed",
    "700": "#6d28d9",
    "800": "#5b21b6"
  },
  "fuchsia": {
    "50": "#fdf4ff",
    "100": "#fae8ff",
    "300": "#f0abfc",
    "500": "#d946ef",
    "600": "#c026d3",
    "700": "#a21caf",
    "800": "#86198f"
  },
  "pink": {
    "50": "#fdf2f8",
    "100": "#fce7f3",
    "300": "#f9a8d4",
    "500": "#ec4899",
    "600": "#db2777",
    "700": "#be185d",
    "800": "#9d174d"
  },
  "amber": {
    "50": "#fffbeb",
    "100": "#fef3c7",
    "300": "#fcd34d",
    "500": "#f59e0b",
    "600": "#d97706",
    "700": "#b45309",
    "800": "#92400e"
  },
  "orange": {
    "50": "#fff7ed",
    "100": "#ffedd5",
    "300": "#fdba74",
    "500": "#f97316",
    "600": "#ea580c",
    "700": "#c2410c",
    "800": "#9a3412"
  },
  "red": {
    "50": "#fef2f2",
    "100": "#fee2e2",
    "300": "#fca5a5",
    "500": "#ef4444",
    "600": "#dc2626",
    "700": "#b91c1c",
    "800": "#991b1b"
  },
  "lime": {
    "50": "#f7fee7",
    "100": "#ecfccb",
    "300": "#bef264",
    "500": "#84cc16",
    "600": "#65a30d",
    "700": "#4d7c0f",
    "800": "#3f6212"
  },
  "stone": {
    "50": "#fafaf9",
    "100": "#f5f5f4",
    "300": "#d6d3d1",
    "500": "#a8a29e",
    "600": "#78716c",
    "700": "#57534e",
    "800": "#44403c"
  },
  "slate": {
    "50": "#f8fafc",
    "100": "#f1f5f9",
    "200": "#e2e8f0",
    "300": "#cbd5e1",
    "400": "#94a3b8",
    "500": "#64748b",
    "600": "#475569",
    "700": "#334155",
    "800": "#1e293b",
    "900": "#0f172a"
  }
} as const;

export const SEMANTIC = {
  "text": "#0f172a",
  "text-muted": "#475569",
  "border": "#e2e8f0",
  "canvas": "#f8fafc",
  "surface": "#ffffff",
  "primary": "#0b7d5e",
  "primary-hover": "#096b50",
  "primary-soft": "#e8f5f0",
  "on-primary": "#ffffff",
  "danger": "#dc2626",
  "danger-hover": "#b91c1c",
  "focus": "#0b7d5e",
  "link": "#096b50"
} as const;

export type StatusKey = "draft" | "planned" | "dispatched" | "in_transit" | "delivered" | "delayed" | "exception" | "cancelled" | "ok" | "warning" | "critical" | "paid" | "overdue" | "open" | "partial";

export interface StatusToken {
  hue: string;
  icon: string;
  label: string;
  strike: boolean;
  bg: string;
  fg: string;
  dot: string;
  border: string;
}

export const STATUS: Record<StatusKey, StatusToken> = {
  "draft": {
    "hue": "slate",
    "icon": "CircleDashed",
    "label": "Draft",
    "strike": false,
    "bg": "#f1f5f9",
    "fg": "#1e293b",
    "dot": "#475569",
    "border": "#cbd5e1"
  },
  "planned": {
    "hue": "fuchsia",
    "icon": "CalendarClock",
    "label": "Planned",
    "strike": false,
    "bg": "#fae8ff",
    "fg": "#86198f",
    "dot": "#c026d3",
    "border": "#f0abfc"
  },
  "dispatched": {
    "hue": "blue",
    "icon": "Send",
    "label": "Dispatched",
    "strike": false,
    "bg": "#dbeafe",
    "fg": "#1e40af",
    "dot": "#2563eb",
    "border": "#93c5fd"
  },
  "in_transit": {
    "hue": "cyan",
    "icon": "Truck",
    "label": "In transit",
    "strike": false,
    "bg": "#cffafe",
    "fg": "#155e75",
    "dot": "#0891b2",
    "border": "#67e8f9"
  },
  "delivered": {
    "hue": "brand",
    "icon": "Check",
    "label": "Delivered",
    "strike": false,
    "bg": "#c6e8db",
    "fg": "#064e3b",
    "dot": "#0b7d5e",
    "border": "#5cc9a7"
  },
  "delayed": {
    "hue": "amber",
    "icon": "Clock",
    "label": "Delayed",
    "strike": false,
    "bg": "#fef3c7",
    "fg": "#92400e",
    "dot": "#d97706",
    "border": "#fcd34d"
  },
  "exception": {
    "hue": "red",
    "icon": "TriangleAlert",
    "label": "Exception",
    "strike": false,
    "bg": "#fee2e2",
    "fg": "#991b1b",
    "dot": "#dc2626",
    "border": "#fca5a5"
  },
  "cancelled": {
    "hue": "stone",
    "icon": "X",
    "label": "Cancelled",
    "strike": true,
    "bg": "#f5f5f4",
    "fg": "#44403c",
    "dot": "#78716c",
    "border": "#d6d3d1"
  },
  "ok": {
    "hue": "brand",
    "icon": "CircleCheck",
    "label": "OK",
    "strike": false,
    "bg": "#c6e8db",
    "fg": "#064e3b",
    "dot": "#0b7d5e",
    "border": "#5cc9a7"
  },
  "warning": {
    "hue": "amber",
    "icon": "CircleAlert",
    "label": "Warning",
    "strike": false,
    "bg": "#fef3c7",
    "fg": "#92400e",
    "dot": "#d97706",
    "border": "#fcd34d"
  },
  "critical": {
    "hue": "red",
    "icon": "OctagonAlert",
    "label": "Critical",
    "strike": false,
    "bg": "#fee2e2",
    "fg": "#991b1b",
    "dot": "#dc2626",
    "border": "#fca5a5"
  },
  "paid": {
    "hue": "brand",
    "icon": "BadgeCheck",
    "label": "Paid",
    "strike": false,
    "bg": "#c6e8db",
    "fg": "#064e3b",
    "dot": "#0b7d5e",
    "border": "#5cc9a7"
  },
  "overdue": {
    "hue": "orange",
    "icon": "CalendarX",
    "label": "Overdue",
    "strike": false,
    "bg": "#ffedd5",
    "fg": "#9a3412",
    "dot": "#ea580c",
    "border": "#fdba74"
  },
  "open": {
    "hue": "blue",
    "icon": "FileText",
    "label": "Open",
    "strike": false,
    "bg": "#dbeafe",
    "fg": "#1e40af",
    "dot": "#2563eb",
    "border": "#93c5fd"
  },
  "partial": {
    "hue": "blue",
    "icon": "CircleDollarSign",
    "label": "Partially paid",
    "strike": false,
    "bg": "#dbeafe",
    "fg": "#1e40af",
    "dot": "#2563eb",
    "border": "#93c5fd"
  }
};

export const STATUS_KEYS = [
  "draft",
  "planned",
  "dispatched",
  "in_transit",
  "delivered",
  "delayed",
  "exception",
  "cancelled",
  "ok",
  "warning",
  "critical",
  "paid",
  "overdue",
  "open",
  "partial"
] as StatusKey[];

export type ProductCode = "GASOLINE_REG" | "GASOLINE_PREM" | "DIESEL_2" | "OFF_ROAD_DIESEL" | "HEATING_OIL" | "KEROSENE" | "ETHANOL_E85" | "PROPANE" | "DEF";

export interface ProductToken {
  name: string | null;
  bg: string;
  fg: string;
  border: string;
  symbol: string;
}

export const PRODUCT: Record<ProductCode | "_unknown", ProductToken> = {
  "GASOLINE_REG": {
    "name": "Regular unleaded",
    "bg": "#ffffff",
    "fg": "#0f172a",
    "border": "#334155",
    "symbol": "R"
  },
  "GASOLINE_PREM": {
    "name": "Premium unleaded",
    "bg": "#dc2626",
    "fg": "#ffffff",
    "border": "#991b1b",
    "symbol": "P"
  },
  "DIESEL_2": {
    "name": "Diesel #2 (on-road)",
    "bg": "#fde047",
    "fg": "#713f12",
    "border": "#a16207",
    "symbol": "D"
  },
  "OFF_ROAD_DIESEL": {
    "name": "Off-road dyed diesel",
    "bg": "#fde047",
    "fg": "#b91c1c",
    "border": "#a16207",
    "symbol": "OFF"
  },
  "HEATING_OIL": {
    "name": "Heating oil (No. 2)",
    "bg": "#166534",
    "fg": "#ffffff",
    "border": "#14532d",
    "symbol": "2"
  },
  "KEROSENE": {
    "name": "Kerosene (K-1)",
    "bg": "#7c4a1e",
    "fg": "#ffffff",
    "border": "#573518",
    "symbol": "K"
  },
  "ETHANOL_E85": {
    "name": "E85 flex fuel",
    "bg": "#9a5b2e",
    "fg": "#ffffff",
    "border": "#6b3d1d",
    "symbol": "E85"
  },
  "PROPANE": {
    "name": "Propane",
    "bg": "#cbd5e1",
    "fg": "#1e293b",
    "border": "#64748b",
    "symbol": "LP"
  },
  "DEF": {
    "name": "Diesel exhaust fluid",
    "bg": "#1d4ed8",
    "fg": "#ffffff",
    "border": "#1e3a8a",
    "symbol": "DEF"
  },
  "_unknown": {
    "name": null,
    "bg": "#f1f5f9",
    "fg": "#1e293b",
    "border": "#64748b",
    "symbol": "?"
  }
};

export const PRODUCT_CODES = [
  "GASOLINE_REG",
  "GASOLINE_PREM",
  "DIESEL_2",
  "OFF_ROAD_DIESEL",
  "HEATING_OIL",
  "KEROSENE",
  "ETHANOL_E85",
  "PROPANE",
  "DEF"
] as ProductCode[];

export const IDENTITY = [
  {
    "token": "blue.600",
    "hex": "#2563eb"
  },
  {
    "token": "pink.600",
    "hex": "#db2777"
  },
  {
    "token": "cyan.700",
    "hex": "#0e7490"
  },
  {
    "token": "amber.700",
    "hex": "#b45309"
  },
  {
    "token": "violet.600",
    "hex": "#7c3aed"
  },
  {
    "token": "brand.600",
    "hex": "#0b7d5e"
  },
  {
    "token": "stone.700",
    "hex": "#57534e"
  },
  {
    "token": "lime.700",
    "hex": "#4d7c0f"
  }
] as const;

export const IDENTITY_ADJACENCY_AVOID = [
  [
    "blue.600",
    "violet.600"
  ]
] as const;

export const CHART = [
  "#2563eb",
  "#db2777",
  "#0891b2",
  "#d97706",
  "#7c3aed",
  "#0b7d5e",
  "#4d7c0f",
  "#78716c"
] as const;

export const CHROME = {
  "topbar": 48,
  "titlerow": 44,
  "toolbar": 44,
  "thead": 36,
  "banner": 32,
  "firstRowBudget": 172
} as const;

export const DENSITY = {
  "comfortable": {
    "row": 40,
    "input": 32
  },
  "compact": {
    "row": 32,
    "input": 28
  }
} as const;

export const FONT = {
  "family": "Inter, system-ui, sans-serif",
  "size": {
    "xs": 12,
    "sm": 13,
    "md": 14,
    "lg": 16,
    "xl": 20
  },
  "weight": {
    "regular": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700
  }
} as const;

export const RADIUS = {
  "sm": 6,
  "md": 8,
  "lg": 10,
  "pill": 999
} as const;

export const SPACE = [
  0,
  4,
  8,
  12,
  16,
  20,
  24,
  32
] as const;

export const DRIVER = {
  "input": 48,
  "tap": 48,
  "body": 16,
  "night": {
    "canvas": "#0b1220",
    "surface": "#111827",
    "text": "#f8fafc",
    "text-muted": "#cbd5e1",
    "border": "#334155",
    "primary": "#16b88c",
    "on-primary": "#052e22"
  }
} as const;
