"""Unit tests for :class:`compliance.services.vcf_calculator.VCFCalculator`.

Covers Task 2.7 of the Fuel Compliance Backbone spec, which asserts the
example-based and boundary behaviors of the ASTM D1250 / API MPMS Ch. 11.1
Table 6B Volume Correction Factor calculator:

* Reference-point behavior at 60 °F — ``VCF == 1.0`` exactly for every
  valid API gravity (Req 2.2).
* Known-point values for common fuel products. The spec brief is explicit
  that we should compute baselines against the shipped polynomial rather
  than pin to the printed D1250 table, because Runsheet's implementation
  is a polynomial approximation. The baselines captured below were
  generated by running ``compute_vcf`` on the target inputs and are
  asserted with ``pytest.approx(rel=1e-3)`` so any *material* change to
  the math is caught while allowing normal floating-point noise.
* Physical invariants: hotter than 60 °F ⇒ VCF < 1 (expansion), colder
  than 60 °F ⇒ VCF > 1 (contraction), and lighter products (higher API
  gravity) swing more per degree than heavier products (Req 2.2).
* Boundary behavior: ``compute_vcf`` at ``MIN_TEMPERATURE_F`` and
  ``MAX_TEMPERATURE_F`` returns a positive finite number; out-of-range
  inputs raise ``ValueError`` prefixed with ``vcf.input_out_of_range``
  (Req 2.6; overlaps Task 2.5, exercised from this angle too).
* Monotonicity: for a fixed API gravity, VCF decreases monotonically as
  temperature rises above 60 °F and increases monotonically as temperature
  drops below it.
* :meth:`compute_net_gallons` rounds to 0.1 gallons (Req 2.3).
* :meth:`default_api_gravity` returns expected defaults for canonical US
  product codes and raises ``ValueError`` for unknown codes (Req 2.8).

Validates: Requirements 2.2, 2.3, 2.6, 2.8
"""
from __future__ import annotations

import math

import pytest

from compliance.services.vcf_calculator import (
    ERROR_CODE_INPUT_OUT_OF_RANGE,
    MAX_API_GRAVITY,
    MAX_TEMPERATURE_F,
    MIN_API_GRAVITY,
    MIN_TEMPERATURE_F,
    REFERENCE_TEMPERATURE_F,
    VCFCalculator,
)


# ---------------------------------------------------------------------------
# Shared calculator instance
#
# The calculator is stateless for its numerical paths, so one instance is
# reused across tests to keep setup cheap and match the pattern used by
# :mod:`tests.unit.test_vcf_calculator_pbt`.
# ---------------------------------------------------------------------------
_CALCULATOR = VCFCalculator()


# ---------------------------------------------------------------------------
# 1. Reference-point behavior — VCF(60°F, any valid API) == 1.0 exactly
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "api_gravity",
    [
        MIN_API_GRAVITY + 1.0,  # 1.0 — avoid the numerically ill-conditioned 0
        10.0,                   # very heavy (residual fuel oil region)
        32.0,                   # heating oil
        35.0,                   # #2 diesel
        43.0,                   # kerosene / jet
        48.0,                   # E85 ethanol blend
        60.0,                   # motor gasoline
        75.0,                   # light naphtha region
        MAX_API_GRAVITY,        # 100.0 — upper bound of validated range
    ],
)
def test_vcf_is_exactly_one_at_reference_temperature(api_gravity: float) -> None:
    """At 60 °F the VCF is 1.0 by definition for every valid API gravity.

    The calculator short-circuits on ``temperature_f == REFERENCE_TEMPERATURE_F``
    (see :meth:`VCFCalculator.compute_vcf`), so the equality here is bit-exact
    rather than approximate — we use ``==`` on purpose to pin that contract.

    Validates: Requirement 2.2
    """
    vcf = _CALCULATOR.compute_vcf(
        temperature_f=REFERENCE_TEMPERATURE_F,
        api_gravity=api_gravity,
    )
    assert vcf == 1.0


# ---------------------------------------------------------------------------
# 2. Known-point VCF values for common fuel products
#
# The three baselines below were generated from the shipped polynomial
# (not the printed ASTM D1250 table) per the task brief: our VCF is a
# polynomial approximation, so the "known values" we pin are the ones the
# implementation produces, with a ``rel=1e-3`` tolerance. Any change to
# the Table 6B constants or the alpha_60 formula will move these numbers
# outside that envelope.
# ---------------------------------------------------------------------------

# (temperature_f, api_gravity, expected_vcf)
KNOWN_POINT_VCFS = [
    pytest.param(80.0, 60.0, 0.9938050223647413, id="gasoline_60api_at_80F"),
    pytest.param(80.0, 35.0, 0.9948561939378365, id="diesel_35api_at_80F"),
    pytest.param(40.0, 35.0, 1.005127979044618, id="diesel_35api_at_40F"),
]


@pytest.mark.parametrize(
    ("temperature_f", "api_gravity", "expected_vcf"),
    KNOWN_POINT_VCFS,
)
def test_vcf_matches_known_baseline_within_tolerance(
    temperature_f: float,
    api_gravity: float,
    expected_vcf: float,
) -> None:
    """Known-point VCFs track the polynomial baseline to rel=1e-3.

    The ``rel=1e-3`` envelope is an order of magnitude looser than the
    typical floating-point noise of the Table 6B polynomial but tight
    enough to flag a coefficient change (which shifts the result by
    percents, not per-mille).

    Validates: Requirement 2.2
    """
    vcf = _CALCULATOR.compute_vcf(
        temperature_f=temperature_f,
        api_gravity=api_gravity,
    )
    assert vcf == pytest.approx(expected_vcf, rel=1e-3)


@pytest.mark.parametrize(
    ("temperature_f", "api_gravity", "_expected"),
    KNOWN_POINT_VCFS,
)
def test_vcf_in_physically_reasonable_range(
    temperature_f: float,
    api_gravity: float,
    _expected: float,
) -> None:
    """Every known-point VCF lands inside the physically plausible envelope.

    Petroleum products in the validated API-gravity window experience
    roughly ±5% volume change across the -50..150 °F temperature range;
    for the realistic 40..80 °F operating envelope exercised here the
    VCF must land comfortably inside ``[0.95, 1.05]``. A VCF outside that
    band indicates either a coefficient regression or a unit-conversion
    bug (the latter tends to produce VCFs around 0.5 or 2.0 when it hits).

    Validates: Requirement 2.2
    """
    vcf = _CALCULATOR.compute_vcf(
        temperature_f=temperature_f,
        api_gravity=api_gravity,
    )
    assert 0.95 <= vcf <= 1.05, (
        f"VCF {vcf!r} at T={temperature_f}°F, API={api_gravity} falls "
        "outside the [0.95, 1.05] physically-plausible range"
    )


# ---------------------------------------------------------------------------
# 3. Physical invariants — sign of the VCF delta around 60 °F
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "api_gravity",
    [10.0, 20.0, 35.0, 50.0, 70.0, 90.0],
)
def test_hotter_than_reference_produces_expansion_vcf_less_than_one(
    api_gravity: float,
) -> None:
    """Above 60 °F fuel has expanded ⇒ net/gross < 1 ⇒ VCF < 1.

    Validates: Requirement 2.2
    """
    vcf = _CALCULATOR.compute_vcf(
        temperature_f=REFERENCE_TEMPERATURE_F + 20.0,  # 80 °F
        api_gravity=api_gravity,
    )
    assert vcf < 1.0, (
        f"Expected VCF < 1 for hot fuel (API={api_gravity}), got {vcf!r}"
    )


@pytest.mark.parametrize(
    "api_gravity",
    [10.0, 20.0, 35.0, 50.0, 70.0, 90.0],
)
def test_colder_than_reference_produces_contraction_vcf_greater_than_one(
    api_gravity: float,
) -> None:
    """Below 60 °F fuel has contracted ⇒ net/gross > 1 ⇒ VCF > 1.

    Validates: Requirement 2.2
    """
    vcf = _CALCULATOR.compute_vcf(
        temperature_f=REFERENCE_TEMPERATURE_F - 20.0,  # 40 °F
        api_gravity=api_gravity,
    )
    assert vcf > 1.0, (
        f"Expected VCF > 1 for cold fuel (API={api_gravity}), got {vcf!r}"
    )


def test_lighter_products_swing_more_per_degree_than_heavier_products() -> None:
    """Higher API gravity ⇒ larger thermal-expansion coefficient.

    The Table 6B polynomial is monotonic in ``alpha_60`` with respect to
    API gravity: a lighter product (higher API) has a smaller density and
    therefore a larger expansion coefficient, so its VCF moves further
    from 1.0 for the same temperature delta. Pinning this at 80 °F (20 °F
    above the reference) protects against accidental sign flips in the
    density-to-alpha conversion.

    Validates: Requirement 2.2
    """
    temperature_f = REFERENCE_TEMPERATURE_F + 20.0  # 80 °F — consistent delta

    heavy_api = 20.0    # residual fuel oil territory
    medium_api = 35.0   # #2 diesel
    light_api = 60.0    # motor gasoline

    vcf_heavy = _CALCULATOR.compute_vcf(temperature_f=temperature_f, api_gravity=heavy_api)
    vcf_medium = _CALCULATOR.compute_vcf(temperature_f=temperature_f, api_gravity=medium_api)
    vcf_light = _CALCULATOR.compute_vcf(temperature_f=temperature_f, api_gravity=light_api)

    swing_heavy = abs(1.0 - vcf_heavy)
    swing_medium = abs(1.0 - vcf_medium)
    swing_light = abs(1.0 - vcf_light)

    assert swing_heavy < swing_medium < swing_light, (
        "Expected |1 - VCF| to grow with API gravity (heavier → less swing); "
        f"got heavy={swing_heavy}, medium={swing_medium}, light={swing_light}"
    )


# ---------------------------------------------------------------------------
# 4. Boundary behavior
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "temperature_f",
    [MIN_TEMPERATURE_F, MAX_TEMPERATURE_F],
)
@pytest.mark.parametrize(
    "api_gravity",
    [10.0, 35.0, 60.0, 90.0],
)
def test_vcf_at_temperature_boundaries_is_positive_and_finite(
    temperature_f: float,
    api_gravity: float,
) -> None:
    """The calculator must survive both ends of the validated temperature range.

    A NaN or infinite return here would signal either a numerical blow-up
    in the exponent or an accidental divide-by-zero in the alpha_60 path.

    Validates: Requirement 2.6
    """
    vcf = _CALCULATOR.compute_vcf(
        temperature_f=temperature_f,
        api_gravity=api_gravity,
    )
    assert math.isfinite(vcf), f"VCF must be finite, got {vcf!r}"
    assert vcf > 0.0, f"VCF must be strictly positive, got {vcf!r}"


@pytest.mark.parametrize(
    ("temperature_f", "api_gravity"),
    [
        (MIN_TEMPERATURE_F - 0.1, 35.0),   # just below lower temp bound
        (MAX_TEMPERATURE_F + 0.1, 35.0),   # just above upper temp bound
        (-200.0, 35.0),                    # far below lower temp bound
        (500.0, 35.0),                     # far above upper temp bound
        (72.0, MIN_API_GRAVITY - 0.1),     # just below lower API bound
        (72.0, MAX_API_GRAVITY + 0.1),     # just above upper API bound
        (72.0, -10.0),                     # far below lower API bound
        (72.0, 250.0),                     # far above upper API bound
    ],
)
def test_vcf_rejects_out_of_range_inputs_with_documented_error_code(
    temperature_f: float,
    api_gravity: float,
) -> None:
    """Inputs outside the validated ranges raise ``vcf.input_out_of_range``.

    Overlaps Task 2.5 but worth re-exercising from the consumer angle —
    callers that catch ``ValueError`` on ``compute_vcf`` rely on the error
    message prefix to distinguish "bad input" from any other ValueError
    the calculator might one day raise.

    Validates: Requirement 2.6
    """
    with pytest.raises(ValueError) as excinfo:
        _CALCULATOR.compute_vcf(
            temperature_f=temperature_f,
            api_gravity=api_gravity,
        )
    assert str(excinfo.value).startswith(ERROR_CODE_INPUT_OUT_OF_RANGE), (
        f"Expected error message to start with {ERROR_CODE_INPUT_OUT_OF_RANGE!r}, "
        f"got {str(excinfo.value)!r}"
    )


def test_compute_net_gallons_propagates_out_of_range_error() -> None:
    """``compute_net_gallons`` shares the validation contract with ``compute_vcf``.

    Validates: Requirement 2.6
    """
    with pytest.raises(ValueError) as excinfo:
        _CALCULATOR.compute_net_gallons(
            gross_gallons=1000.0,
            temperature_f=MAX_TEMPERATURE_F + 1.0,
            api_gravity=35.0,
        )
    assert str(excinfo.value).startswith(ERROR_CODE_INPUT_OUT_OF_RANGE)


def test_compute_net_gallons_rejects_negative_gross() -> None:
    """Negative gross gallons is a structurally invalid measurement.

    Validates: Requirement 2.3
    """
    with pytest.raises(ValueError):
        _CALCULATOR.compute_net_gallons(
            gross_gallons=-1.0,
            temperature_f=72.0,
            api_gravity=35.0,
        )


# ---------------------------------------------------------------------------
# 5. Monotonicity around 60 °F
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "api_gravity",
    [20.0, 35.0, 60.0, 90.0],
)
def test_vcf_decreases_monotonically_as_temperature_rises_above_reference(
    api_gravity: float,
) -> None:
    """For fixed API gravity, ``compute_vcf`` is strictly decreasing in T for T > 60°F.

    Sampling every 5 °F from 60 to 150 gives 19 points — enough resolution
    to pin monotonicity without paying the cost of a per-degree sweep.

    Validates: Requirement 2.2
    """
    temperatures = [REFERENCE_TEMPERATURE_F + 5.0 * i for i in range(0, 19)]
    vcfs = [
        _CALCULATOR.compute_vcf(temperature_f=t, api_gravity=api_gravity)
        for t in temperatures
    ]

    for prev, curr, t_prev, t_curr in zip(vcfs, vcfs[1:], temperatures, temperatures[1:]):
        assert curr < prev, (
            f"VCF not monotonically decreasing above 60°F (API={api_gravity}): "
            f"VCF({t_prev})={prev} vs VCF({t_curr})={curr}"
        )


@pytest.mark.parametrize(
    "api_gravity",
    [20.0, 35.0, 60.0, 90.0],
)
def test_vcf_increases_monotonically_as_temperature_drops_below_reference(
    api_gravity: float,
) -> None:
    """For fixed API gravity, ``compute_vcf`` is strictly increasing as T drops below 60°F.

    Sampling every 5 °F from 60 down to -50 gives 23 points.

    Validates: Requirement 2.2
    """
    temperatures = [REFERENCE_TEMPERATURE_F - 5.0 * i for i in range(0, 23)]
    vcfs = [
        _CALCULATOR.compute_vcf(temperature_f=t, api_gravity=api_gravity)
        for t in temperatures
    ]

    for prev, curr, t_prev, t_curr in zip(vcfs, vcfs[1:], temperatures, temperatures[1:]):
        assert curr > prev, (
            f"VCF not monotonically increasing below 60°F (API={api_gravity}): "
            f"VCF({t_prev})={prev} vs VCF({t_curr})={curr}"
        )


# ---------------------------------------------------------------------------
# 6. compute_net_gallons rounding
# ---------------------------------------------------------------------------


def test_compute_net_gallons_rounds_to_one_decimal_place() -> None:
    """8000 gallons at 72 °F / 35 °API produces the rounded net baseline.

    The expected value was captured from the shipped polynomial (the
    equivalent of running ``compute_net_gallons(8000, 72, 35)`` once) so
    regressions in either the VCF math or the rounding digit count are
    caught. Using ``==`` against the exact baseline is safe here because
    ``compute_net_gallons`` rounds to one decimal — the result is always
    representable exactly in floating point for a 0.1-gallon granularity
    at this magnitude.

    Validates: Requirement 2.3
    """
    gross_gallons = 8_000.0
    temperature_f = 72.0  # ambient above 60 °F ⇒ expect net < gross
    api_gravity = 35.0    # #2 diesel

    net_gallons = _CALCULATOR.compute_net_gallons(
        gross_gallons=gross_gallons,
        temperature_f=temperature_f,
        api_gravity=api_gravity,
    )

    # Baseline captured from the polynomial implementation (Task 2.7 brief
    # explicitly states we should use the implementation as the reference,
    # not printed table values).
    assert net_gallons == pytest.approx(7975.3, abs=0.05)

    # Separately pin the rounding contract so a regression in the rounding
    # digit count (e.g. round(net, 2)) is caught even if the math drifts.
    assert net_gallons == round(net_gallons, 1)
    # And the absolute tolerance above is one rounding step — anything
    # larger would let through a truly wrong VCF.


def test_compute_net_gallons_is_less_than_gross_when_hot() -> None:
    """Sanity: hot fuel has expanded so the rounded net must be < gross.

    Validates: Requirement 2.3
    """
    gross_gallons = 8_000.0
    net_gallons = _CALCULATOR.compute_net_gallons(
        gross_gallons=gross_gallons,
        temperature_f=80.0,
        api_gravity=35.0,
    )
    assert net_gallons < gross_gallons


def test_compute_net_gallons_is_greater_than_gross_when_cold() -> None:
    """Sanity: cold fuel has contracted so the rounded net must be > gross.

    Validates: Requirement 2.3
    """
    gross_gallons = 8_000.0
    net_gallons = _CALCULATOR.compute_net_gallons(
        gross_gallons=gross_gallons,
        temperature_f=40.0,
        api_gravity=35.0,
    )
    assert net_gallons > gross_gallons


def test_compute_net_gallons_equals_gross_at_reference_temperature() -> None:
    """At 60 °F the VCF is exactly 1 ⇒ net == gross exactly.

    Validates: Requirements 2.2, 2.3
    """
    gross_gallons = 8_000.0
    net_gallons = _CALCULATOR.compute_net_gallons(
        gross_gallons=gross_gallons,
        temperature_f=REFERENCE_TEMPERATURE_F,
        api_gravity=35.0,
    )
    assert net_gallons == gross_gallons


# ---------------------------------------------------------------------------
# 7. default_api_gravity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("product_code", "expected_api_gravity"),
    [
        ("DIESEL_2", 35.0),
        ("OFF_ROAD_DIESEL", 35.0),
        ("HEATING_OIL", 32.0),
        ("GASOLINE_REG", 60.0),
        ("GASOLINE_PREM", 60.0),
        ("KEROSENE", 43.0),
        ("PROPANE", 147.0),
        ("ETHANOL_E85", 48.0),
        ("DEF", 10.0),
    ],
)
def test_default_api_gravity_returns_expected_default_for_canonical_product(
    product_code: str,
    expected_api_gravity: float,
) -> None:
    """Every canonical US product code has a module-level default gravity.

    Validates: Requirement 2.8
    """
    result = _CALCULATOR.default_api_gravity(product_code)
    assert result == expected_api_gravity


def test_default_api_gravity_accepts_legacy_alias() -> None:
    """Legacy aliases (e.g. NG ``AGO`` ⇒ ``DIESEL_2``) canonicalize first.

    This pins the contract that callers can pass either canonical codes
    or legacy region-specific aliases without hitting the "unknown
    product" branch.

    Validates: Requirement 2.8
    """
    assert _CALCULATOR.default_api_gravity("AGO") == 35.0
    assert _CALCULATOR.default_api_gravity("PMS") == 60.0
    assert _CALCULATOR.default_api_gravity("LPG") == 147.0


@pytest.mark.parametrize(
    "product_code",
    [
        "NOT_A_REAL_PRODUCT",
        "",
        "RANDOM_STRING",
    ],
)
def test_default_api_gravity_raises_value_error_for_unknown_product(
    product_code: str,
) -> None:
    """Unknown product codes surface as ``ValueError``, not catalog errors.

    ``UnknownFuelProductError`` is a ``ValueError`` subclass, so catching
    ``ValueError`` is the documented pattern; we assert it here to lock
    in the contract that callers don't need to know about the catalog's
    internal error hierarchy.

    Validates: Requirement 2.8
    """
    with pytest.raises(ValueError):
        _CALCULATOR.default_api_gravity(product_code)
