"""
Pydantic v2 models for the Customer Notification Pipeline.

Defines validated models matching the Elasticsearch index field structures
for outbound customer notifications across SMS, email, and WhatsApp channels.
These models are used for request/response validation in REST endpoints and
internal service communication.

Requirements: 3.1, 4.1, 5.1, 7.3, 12.1
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class NotificationType(str, Enum):
    """Type of customer notification generated by the pipeline.

    Validates: Requirement 1.1, 1.2, 1.3, 1.4
    """

    DELIVERY_CONFIRMATION = "delivery_confirmation"
    DELAY_ALERT = "delay_alert"
    ETA_CHANGE = "eta_change"
    ORDER_STATUS_UPDATE = "order_status_update"


class DeliveryStatus(str, Enum):
    """Lifecycle status of a notification delivery.

    Valid transitions: pending → sent → delivered,
    pending → failed, sent → failed.

    Validates: Requirement 3.1
    """

    PENDING = "pending"
    SENT = "sent"
    DELIVERED = "delivered"
    FAILED = "failed"


class Channel(str, Enum):
    """Supported notification delivery channels.

    Validates: Requirement 2.1
    """

    SMS = "sms"
    EMAIL = "email"
    WHATSAPP = "whatsapp"


# ---------------------------------------------------------------------------
# Data models (matching ES index field structures)
# ---------------------------------------------------------------------------


class Notification(BaseModel):
    """Model for the ``notifications_current`` Elasticsearch index.

    Validates: Requirements 3.1, 12.1
    """

    notification_id: str
    notification_type: NotificationType
    channel: Channel
    recipient_reference: str
    recipient_name: Optional[str] = None
    subject: Optional[str] = None
    message_body: str
    related_entity_type: Optional[str] = None  # "order", "job", "shipment"
    related_entity_id: Optional[str] = None
    delivery_status: DeliveryStatus = DeliveryStatus.PENDING
    created_at: str
    updated_at: str
    sent_at: Optional[str] = None
    delivered_at: Optional[str] = None
    failed_at: Optional[str] = None
    failure_reason: Optional[str] = None
    retry_count: int = 0
    tenant_id: str


class EventPreference(BaseModel):
    """Per-event-type channel selection within a customer preference.

    Validates: Requirement 4.1
    """

    event_type: str
    enabled_channels: list[Channel]


class NotificationPreference(BaseModel):
    """Model for the ``notification_preferences`` Elasticsearch index.

    Validates: Requirement 4.1
    """

    preference_id: str
    tenant_id: str
    customer_id: str
    customer_name: str
    channels: dict[str, str]  # {"sms": "+254...", "email": "user@example.com", ...}
    event_preferences: list[EventPreference]
    created_at: str
    updated_at: str


class NotificationTemplate(BaseModel):
    """Model for the ``notification_templates`` Elasticsearch index.

    Validates: Requirement 5.1
    """

    template_id: str
    tenant_id: str
    event_type: str
    channel: Channel
    subject_template: Optional[str] = None
    body_template: str
    placeholders: list[str]
    created_at: str
    updated_at: str


class NotificationRule(BaseModel):
    """Model for the ``notification_rules`` Elasticsearch index.

    Validates: Requirement 7.3
    """

    rule_id: str
    tenant_id: str
    event_type: str
    enabled: bool = True
    default_channels: list[Channel]
    template_id: Optional[str] = None
    created_at: str
    updated_at: str
