"""Asset Certification Service — Fleet certification management and dispatch eligibility.

Implements the ``Asset_Certification_Service`` described in design §13 of the
Fuel Compliance Backbone spec. This service manages vehicle/trailer
certification records (DOT cargo tank inspections V/K/I/P/UT, meter seal,
fire extinguisher) and provides:

* CRUD operations for AssetCertification records in the
  ``asset_certifications`` ES index.
* ``check_expiry_alerts()`` — daily cron scanning all certifications for
  upcoming expirations at 60/30/7-day thresholds. (Task 8.3)
* ``is_dispatch_eligible()`` — checks whether an asset meets dispatch
  requirements based on certification validity. (Task 8.5)
* ``get_fleet_dashboard()`` — tenant-wide fleet certification dashboard.
  (Task 8.7)

All queries are tenant-scoped via ``inject_tenant_filter`` (Constraint C3).

Validates: Requirement 13.1
"""

from __future__ import annotations

import logging
from datetime import date, datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from compliance.models.asset_certification import AssetCertification, CertificationType
from compliance.services.compliance_es_mappings import ASSET_CERTIFICATIONS_INDEX
from errors.exceptions import resource_not_found, validation_error
from ops.middleware.tenant_guard import inject_tenant_filter
from services.elasticsearch_service import ElasticsearchService
from services.time_utils import utcnow

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_PAGE_LIMIT = 50
_MAX_PAGE_LIMIT = 200

# Alert thresholds in days (Req 13.2, 13.3, 13.4)
ALERT_THRESHOLD_WARNING_DAYS = 60
ALERT_THRESHOLD_URGENT_DAYS = 30
ALERT_THRESHOLD_CRITICAL_DAYS = 7

# DOT cargo tank certification types that block dispatch when expired (Req 13.5)
DOT_CARGO_TANK_CERT_TYPES = {"V_test", "K_test", "I_test", "P_test", "UT_test"}

# 3-year retest interval in days (Req 13.6) — approximately 1095 days
RETEST_INTERVAL_DAYS = 1095


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class CertAlert(BaseModel):
    """Expiry alert generated by check_expiry_alerts."""

    model_config = ConfigDict(extra="forbid")

    cert_id: str
    asset_id: str
    tenant_id: str
    certification_type: str
    expiry_date: date
    days_until_expiry: int
    severity: str  # warning | urgent | critical
    generated_at: datetime = Field(default_factory=utcnow)


class AssetEligibility(BaseModel):
    """Result of dispatch eligibility check for an asset."""

    model_config = ConfigDict(extra="forbid")

    asset_id: str
    eligible: bool
    reasons: List[str] = Field(default_factory=list)


class CertificationSummary(BaseModel):
    """Summary entry for the fleet certification dashboard."""

    model_config = ConfigDict(extra="forbid")

    asset_id: str
    certification_type: str
    cert_id: str
    certification_date: date
    expiry_date: date
    status: str
    days_until_expiry: int
    inspector_name: str
    certificate_number: str


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class AssetCertificationService:
    """Service layer for Asset Certification management.

    Provides CRUD operations for AssetCertification records and
    certification compliance checks. Every public method takes
    ``tenant_id`` as its first positional argument and every
    Elasticsearch query is wrapped with ``inject_tenant_filter`` to
    enforce strict tenant isolation (Constraint C3).

    Args:
        es_service: Elasticsearch handle for querying the
            ``asset_certifications`` index.

    Validates: Requirement 13.1
    """

    def __init__(self, es_service: ElasticsearchService) -> None:
        self._es = es_service

    # ------------------------------------------------------------------
    # Create
    # ------------------------------------------------------------------

    async def create(
        self,
        tenant_id: str,
        *,
        asset_id: str,
        certification_type: str,
        certification_date: date,
        expiry_date: date,
        inspector_name: str,
        certificate_number: str,
        status: str = "valid",
    ) -> Dict[str, Any]:
        """Create a new AssetCertification record.

        Validates the input via the AssetCertification Pydantic model,
        assigns a server-generated ``cert_id``, and persists to ES.

        When the new certification has status "valid", any dispatch
        restrictions from previously expired certifications of the same
        type for the same asset are automatically cleared (Req 13.8).

        Validates: Requirement 13.1, 13.8
        """
        cert = AssetCertification(
            tenant_id=tenant_id,
            asset_id=asset_id,
            certification_type=certification_type,
            certification_date=certification_date,
            expiry_date=expiry_date,
            inspector_name=inspector_name,
            certificate_number=certificate_number,
            status=status,
        )

        doc = self._serialize_cert(cert)

        await self._es.index_document(
            ASSET_CERTIFICATIONS_INDEX, cert.cert_id, doc
        )

        logger.info(
            "Created asset certification %s (type=%s, asset=%s) for tenant %s",
            cert.cert_id,
            certification_type,
            asset_id,
            tenant_id,
        )

        # Req 13.8: When a new valid certification is recorded, clear
        # dispatch restrictions from previously expired certs of the same type.
        if status == "valid":
            await self.clear_dispatch_restrictions(
                tenant_id, asset_id, certification_type
            )

        return doc

    # ------------------------------------------------------------------
    # Clear dispatch restrictions (Task 8.8)
    # ------------------------------------------------------------------

    async def clear_dispatch_restrictions(
        self,
        tenant_id: str,
        asset_id: str,
        certification_type: str,
    ) -> int:
        """Clear dispatch restrictions for an asset's certification type.

        Finds any expired certifications of the given type for the asset
        and marks them as superseded by updating their status to
        "superseded". This ensures that ``is_dispatch_eligible()`` no
        longer blocks the asset due to old expired certifications now
        that a new valid certification exists.

        Returns the number of expired certifications that were cleared.

        Validates: Requirement 13.8
        """
        # Query expired certs of the same type for the same asset
        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": [
                        {"term": {"asset_id": asset_id}},
                        {"term": {"certification_type": certification_type}},
                        {"term": {"status": "expired"}},
                    ]
                }
            },
            "size": _MAX_PAGE_LIMIT,
            "sort": [
                {"expiry_date": {"order": "asc"}},
                {"cert_id": {"order": "asc"}},
            ],
        }
        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            ASSET_CERTIFICATIONS_INDEX, query, size=_MAX_PAGE_LIMIT
        )

        hits = response["hits"]["hits"]
        cleared_count = 0

        for hit in hits:
            cert_doc = hit["_source"]
            cert_id = cert_doc.get("cert_id", "")

            try:
                partial: Dict[str, Any] = {
                    "status": "superseded",
                    "updated_at": utcnow().isoformat(),
                }
                await self._es.update_document(
                    ASSET_CERTIFICATIONS_INDEX, cert_id, partial
                )
                cleared_count += 1
                logger.info(
                    "Cleared dispatch restriction: certification %s "
                    "(type=%s, asset=%s) marked superseded for tenant %s",
                    cert_id,
                    certification_type,
                    asset_id,
                    tenant_id,
                )
            except Exception as exc:
                logger.error(
                    "Failed to clear dispatch restriction for cert %s: %s",
                    cert_id,
                    exc,
                )

        if cleared_count > 0:
            logger.info(
                "Cleared %d dispatch restriction(s) for asset %s "
                "(type=%s) in tenant %s",
                cleared_count,
                asset_id,
                certification_type,
                tenant_id,
            )

        return cleared_count

    # ------------------------------------------------------------------
    # Get
    # ------------------------------------------------------------------

    async def get(self, tenant_id: str, cert_id: str) -> Dict[str, Any]:
        """Retrieve a single AssetCertification by ID, scoped to tenant.

        Raises resource_not_found if the certification does not exist or
        does not belong to the specified tenant.

        Validates: Requirement 13.1, Constraint C3
        """
        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": [
                        {"term": {"cert_id": cert_id}},
                    ]
                }
            },
            "size": 1,
        }
        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            ASSET_CERTIFICATIONS_INDEX, query, size=1
        )

        hits = response["hits"]["hits"]
        if not hits:
            raise resource_not_found(
                f"Asset certification '{cert_id}' not found",
                details={"cert_id": cert_id},
            )

        return hits[0]["_source"]

    # ------------------------------------------------------------------
    # List
    # ------------------------------------------------------------------

    async def list(
        self,
        tenant_id: str,
        *,
        asset_id: Optional[str] = None,
        certification_type: Optional[str] = None,
        status: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: int = _DEFAULT_PAGE_LIMIT,
    ) -> Dict[str, Any]:
        """List AssetCertifications for a tenant with cursor/limit pagination.

        Supports optional filtering by asset_id, certification_type, and
        status. Default limit is 50, max 200. Cursor is the ``cert_id``
        of the last item on the previous page (keyset pagination via
        ``search_after``).

        Validates: Requirement 13.1, Constraint C3
        """
        if limit < 1:
            limit = _DEFAULT_PAGE_LIMIT
        if limit > _MAX_PAGE_LIMIT:
            limit = _MAX_PAGE_LIMIT

        must_clauses: List[Dict[str, Any]] = []
        if asset_id:
            must_clauses.append({"term": {"asset_id": asset_id}})
        if certification_type:
            must_clauses.append({"term": {"certification_type": certification_type}})
        if status:
            must_clauses.append({"term": {"status": status}})

        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": must_clauses if must_clauses else [{"match_all": {}}],
                }
            },
            "size": limit,
            "sort": [
                {"expiry_date": {"order": "asc"}},
                {"cert_id": {"order": "asc"}},
            ],
        }

        if cursor:
            base_query["search_after"] = [cursor, cursor]

        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            ASSET_CERTIFICATIONS_INDEX, query, size=limit
        )

        hits = response["hits"]["hits"]
        items = [hit["_source"] for hit in hits]

        next_cursor: Optional[str] = None
        if hits and len(hits) == limit:
            last_sort = hits[-1].get("sort")
            if last_sort and len(last_sort) >= 2:
                next_cursor = hits[-1]["_source"]["cert_id"]

        return {
            "items": items,
            "next_cursor": next_cursor,
            "limit": limit,
        }

    # ------------------------------------------------------------------
    # Update
    # ------------------------------------------------------------------

    async def update(
        self,
        tenant_id: str,
        cert_id: str,
        *,
        certification_date: Optional[date] = None,
        expiry_date: Optional[date] = None,
        inspector_name: Optional[str] = None,
        certificate_number: Optional[str] = None,
        status: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Update an existing AssetCertification record.

        Only non-None fields are applied. The ``asset_id`` and
        ``certification_type`` are immutable after creation.

        Validates: Requirement 13.1, Constraint C3
        """
        existing = await self.get(tenant_id, cert_id)

        partial: Dict[str, Any] = {}

        if certification_date is not None:
            partial["certification_date"] = certification_date.isoformat()

        if expiry_date is not None:
            partial["expiry_date"] = expiry_date.isoformat()

        if inspector_name is not None:
            stripped = inspector_name.strip()
            if not stripped:
                raise validation_error(
                    "inspector_name must not be empty or whitespace",
                    details={"inspector_name": inspector_name},
                )
            partial["inspector_name"] = stripped

        if certificate_number is not None:
            stripped = certificate_number.strip()
            if not stripped:
                raise validation_error(
                    "certificate_number must not be empty or whitespace",
                    details={"certificate_number": certificate_number},
                )
            partial["certificate_number"] = stripped

        if status is not None:
            if status not in ("valid", "expiring_soon", "expired", "superseded"):
                raise validation_error(
                    "status must be valid, expiring_soon, expired, or superseded",
                    details={"status": status},
                )
            partial["status"] = status

        if not partial:
            return existing

        partial["updated_at"] = utcnow().isoformat()

        await self._es.update_document(
            ASSET_CERTIFICATIONS_INDEX, cert_id, partial
        )

        merged = {**existing, **partial}
        logger.info(
            "Updated asset certification %s for tenant %s",
            cert_id,
            tenant_id,
        )
        return merged

    # ------------------------------------------------------------------
    # Expiry alerts (Task 8.3)
    # ------------------------------------------------------------------

    async def check_expiry_alerts(self, tenant_id: str) -> List[CertAlert]:
        """Scan all certifications for upcoming expirations.

        Queries all non-expired certifications for the tenant and checks
        each certification's expiry_date against today. For each
        certification within 60 days of expiry, generates a CertAlert
        with the appropriate severity:

        - ≤7 days (or already past) → "critical" (Req 13.4)
          Also transitions status to "expired".
        - ≤30 days → "urgent"   (Req 13.3)
        - ≤60 days → "warning"  (Req 13.2)

        Uses paginated ES queries (search_after) to handle large fleets
        without hitting page size limits.

        Validates: Requirements 13.2, 13.3, 13.4
        """
        alerts: List[CertAlert] = []
        today = date.today()

        # Query all non-expired certifications for this tenant
        certifications = await self._get_all_non_expired_certifications(tenant_id)

        for cert_doc in certifications:
            cert_id = cert_doc.get("cert_id", "")
            asset_id = cert_doc.get("asset_id", "")
            certification_type = cert_doc.get("certification_type", "")
            current_status = cert_doc.get("status", "valid")
            expiry_raw = cert_doc.get("expiry_date")

            if expiry_raw is None:
                continue

            expiry_date = self._parse_date(expiry_raw)
            if expiry_date is None:
                continue

            days_until_expiry = (expiry_date - today).days

            # Only generate alerts for dates within 60 days
            if days_until_expiry > ALERT_THRESHOLD_WARNING_DAYS:
                continue

            # Determine severity based on thresholds (most severe first)
            if days_until_expiry <= ALERT_THRESHOLD_CRITICAL_DAYS:
                severity = "critical"
                # Req 13.4: Transition status to expired when ≤7 days or past
                # Idempotent: skip if already expired
                if current_status != "expired":
                    await self._transition_to_expired(tenant_id, cert_id)
            elif days_until_expiry <= ALERT_THRESHOLD_URGENT_DAYS:
                severity = "urgent"
                # Transition valid → expiring_soon when ≤30 days but >7 days
                # Idempotent: skip if already expiring_soon or expired
                if current_status == "valid":
                    await self._transition_to_expiring_soon(tenant_id, cert_id)
            else:
                severity = "warning"

            alert = CertAlert(
                cert_id=cert_id,
                asset_id=asset_id,
                tenant_id=tenant_id,
                certification_type=certification_type,
                expiry_date=expiry_date,
                days_until_expiry=days_until_expiry,
                severity=severity,
            )
            alerts.append(alert)

        logger.info(
            "Generated %d expiry alerts for tenant %s",
            len(alerts),
            tenant_id,
        )
        return alerts

    async def _get_all_non_expired_certifications(
        self, tenant_id: str
    ) -> List[Dict[str, Any]]:
        """Retrieve all non-expired certifications for a tenant using search_after pagination.

        Fetches certifications with status in ("valid", "expiring_soon")
        to avoid re-alerting on already-expired certifications.
        """
        all_certs: List[Dict[str, Any]] = []
        search_after: Optional[list] = None

        while True:
            base_query: Dict[str, Any] = {
                "query": {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "status": ["valid", "expiring_soon"]
                                }
                            },
                        ]
                    }
                },
                "size": _MAX_PAGE_LIMIT,
                "sort": [
                    {"expiry_date": {"order": "asc"}},
                    {"cert_id": {"order": "asc"}},
                ],
            }

            if search_after is not None:
                base_query["search_after"] = search_after

            query = inject_tenant_filter(base_query, tenant_id)

            response = await self._es.search_documents(
                ASSET_CERTIFICATIONS_INDEX, query, size=_MAX_PAGE_LIMIT
            )

            hits = response["hits"]["hits"]
            if not hits:
                break

            for hit in hits:
                all_certs.append(hit["_source"])

            # Set up search_after for next page
            last_sort = hits[-1].get("sort")
            if last_sort:
                search_after = last_sort
            else:
                break

            # If we got fewer than the page size, we're done
            if len(hits) < _MAX_PAGE_LIMIT:
                break

        return all_certs

    async def _transition_to_expired(self, tenant_id: str, cert_id: str) -> None:
        """Transition a certification to expired status.

        Called when a certification is within 7 days of expiry or has
        already passed. Updates the status to "expired" in ES.

        Validates: Requirement 13.4
        """
        try:
            partial: Dict[str, Any] = {
                "status": "expired",
                "updated_at": utcnow().isoformat(),
            }
            await self._es.update_document(
                ASSET_CERTIFICATIONS_INDEX, cert_id, partial
            )
            logger.warning(
                "Transitioned certification %s to expired for tenant %s",
                cert_id,
                tenant_id,
            )
        except Exception as exc:
            logger.error(
                "Failed to transition certification %s to expired: %s",
                cert_id,
                exc,
            )

    async def _transition_to_expiring_soon(self, tenant_id: str, cert_id: str) -> None:
        """Transition a certification from valid to expiring_soon status.

        Called when a certification is within 30 days of expiry but more
        than 7 days away. Only transitions if current status is "valid"
        (idempotent — won't re-transition if already expiring_soon).

        Validates: Requirement 13.4
        """
        try:
            partial: Dict[str, Any] = {
                "status": "expiring_soon",
                "updated_at": utcnow().isoformat(),
            }
            await self._es.update_document(
                ASSET_CERTIFICATIONS_INDEX, cert_id, partial
            )
            logger.info(
                "Transitioned certification %s to expiring_soon for tenant %s",
                cert_id,
                tenant_id,
            )
        except Exception as exc:
            logger.error(
                "Failed to transition certification %s to expiring_soon: %s",
                cert_id,
                exc,
            )

    # ------------------------------------------------------------------
    # Dispatch eligibility (Task 8.5)
    # ------------------------------------------------------------------

    async def is_dispatch_eligible(
        self,
        tenant_id: str,
        asset_id: str,
    ) -> AssetEligibility:
        """Check whether an asset is eligible for dispatch.

        Evaluates all certifications for the asset. An asset is
        ineligible if:
        1. Any DOT cargo tank certification (V/K/I/P/UT) is expired
           (status == "expired" or expiry_date has passed). (Req 13.5)
        2. Any DOT cargo tank certification's certification_date is more
           than 3 years (1095 days) ago AND no newer cert of the same
           type exists for the asset — retest overdue. (Req 13.6)

        Non-DOT certifications (meter_seal, fire_extinguisher) do NOT
        block dispatch.

        Validates: Requirements 13.5, 13.6
        """
        today = date.today()
        reasons: List[str] = []

        # Query all certifications for this asset (all statuses)
        certifications = await self._get_all_certifications_for_asset(
            tenant_id, asset_id
        )

        # --- Check 1: Expired DOT certs (Req 13.5) ---
        for cert_doc in certifications:
            cert_type = cert_doc.get("certification_type", "")

            # Only DOT cargo tank certs block dispatch
            if cert_type not in DOT_CARGO_TANK_CERT_TYPES:
                continue

            status = cert_doc.get("status", "valid")

            # Superseded certs have been replaced by a newer valid cert
            # and should not block dispatch (Req 13.8)
            if status == "superseded":
                continue

            expiry_raw = cert_doc.get("expiry_date")

            # Check if expired by status or by date
            is_expired = status == "expired"

            if not is_expired and expiry_raw is not None:
                expiry_date = self._parse_date(expiry_raw)
                if expiry_date is not None and expiry_date < today:
                    is_expired = True

            if is_expired:
                cert_id = cert_doc.get("cert_id", "unknown")
                reasons.append(
                    f"DOT cargo tank certification '{cert_type}' (cert_id={cert_id}) is expired"
                )

        # --- Check 2: 3-year retest requirement (Req 13.6) ---
        # Group DOT certs by type and find the most recent certification_date
        # for each type. If the most recent is older than RETEST_INTERVAL_DAYS,
        # the asset requires a new certification before dispatch.
        dot_certs_by_type: Dict[str, List[Dict[str, Any]]] = {}
        for cert_doc in certifications:
            cert_type = cert_doc.get("certification_type", "")
            if cert_type not in DOT_CARGO_TANK_CERT_TYPES:
                continue
            # Skip superseded certs — they've been replaced (Req 13.8)
            if cert_doc.get("status") == "superseded":
                continue
            dot_certs_by_type.setdefault(cert_type, []).append(cert_doc)

        for cert_type, certs_of_type in dot_certs_by_type.items():
            # Find the most recent certification_date for this type
            most_recent_cert_date: Optional[date] = None
            for cert_doc in certs_of_type:
                cert_date_raw = cert_doc.get("certification_date")
                if cert_date_raw is None:
                    continue
                cert_date = self._parse_date(cert_date_raw)
                if cert_date is None:
                    continue
                if most_recent_cert_date is None or cert_date > most_recent_cert_date:
                    most_recent_cert_date = cert_date

            if most_recent_cert_date is None:
                continue

            days_since_cert = (today - most_recent_cert_date).days
            if days_since_cert > RETEST_INTERVAL_DAYS:
                reasons.append(
                    f"DOT cargo tank certification '{cert_type}' requires "
                    f"3-year retest (last certified: {most_recent_cert_date.isoformat()})"
                )

        if reasons:
            logger.warning(
                "Asset %s is NOT dispatch-eligible for tenant %s: %s",
                asset_id,
                tenant_id,
                "; ".join(reasons),
            )
            return AssetEligibility(
                asset_id=asset_id,
                eligible=False,
                reasons=reasons,
            )

        return AssetEligibility(asset_id=asset_id, eligible=True)

    async def _get_all_certifications_for_asset(
        self, tenant_id: str, asset_id: str
    ) -> List[Dict[str, Any]]:
        """Retrieve all certifications for a specific asset using search_after pagination.

        Fetches certifications across all statuses (valid, expiring_soon,
        expired) to evaluate dispatch eligibility comprehensively.
        """
        all_certs: List[Dict[str, Any]] = []
        search_after: Optional[list] = None

        while True:
            base_query: Dict[str, Any] = {
                "query": {
                    "bool": {
                        "must": [
                            {"term": {"asset_id": asset_id}},
                        ]
                    }
                },
                "size": _MAX_PAGE_LIMIT,
                "sort": [
                    {"expiry_date": {"order": "asc"}},
                    {"cert_id": {"order": "asc"}},
                ],
            }

            if search_after is not None:
                base_query["search_after"] = search_after

            query = inject_tenant_filter(base_query, tenant_id)

            response = await self._es.search_documents(
                ASSET_CERTIFICATIONS_INDEX, query, size=_MAX_PAGE_LIMIT
            )

            hits = response["hits"]["hits"]
            if not hits:
                break

            for hit in hits:
                all_certs.append(hit["_source"])

            # Set up search_after for next page
            last_sort = hits[-1].get("sort")
            if last_sort:
                search_after = last_sort
            else:
                break

            # If we got fewer than the page size, we're done
            if len(hits) < _MAX_PAGE_LIMIT:
                break

        return all_certs

    # ------------------------------------------------------------------
    # Fleet dashboard (Task 8.7)
    # ------------------------------------------------------------------

    async def get_fleet_dashboard(
        self,
        tenant_id: str,
    ) -> List[CertificationSummary]:
        """Return fleet certification dashboard for a tenant.

        Shows all assets with their certification statuses, upcoming
        expirations, and overdue inspections sorted by urgency (most
        urgent first).

        Logic:
        1. Query ALL certifications for the tenant (all statuses).
        2. For each cert, compute days_until_expiry from today.
        3. Build a CertificationSummary for each cert.
        4. Sort by urgency: expired first (negative days), then by
           days_until_expiry ascending.

        Validates: Requirement 13.7
        """
        today = date.today()

        # Fetch all certifications for this tenant (all statuses)
        all_certs = await self._get_all_certifications_for_tenant(tenant_id)

        summaries: List[CertificationSummary] = []
        for cert_doc in all_certs:
            expiry_raw = cert_doc.get("expiry_date")
            if expiry_raw is None:
                continue

            expiry_date = self._parse_date(expiry_raw)
            if expiry_date is None:
                continue

            cert_date_raw = cert_doc.get("certification_date")
            if cert_date_raw is None:
                continue

            certification_date = self._parse_date(cert_date_raw)
            if certification_date is None:
                continue

            days_until_expiry = (expiry_date - today).days

            summary = CertificationSummary(
                asset_id=cert_doc.get("asset_id", ""),
                certification_type=cert_doc.get("certification_type", ""),
                cert_id=cert_doc.get("cert_id", ""),
                certification_date=certification_date,
                expiry_date=expiry_date,
                status=cert_doc.get("status", "valid"),
                days_until_expiry=days_until_expiry,
                inspector_name=cert_doc.get("inspector_name", ""),
                certificate_number=cert_doc.get("certificate_number", ""),
            )
            summaries.append(summary)

        # Sort by urgency: expired first (negative days_until_expiry),
        # then by days_until_expiry ascending (closest to expiry first)
        summaries.sort(key=lambda s: s.days_until_expiry)

        logger.info(
            "Generated fleet dashboard with %d certifications for tenant %s",
            len(summaries),
            tenant_id,
        )
        return summaries

    async def _get_all_certifications_for_tenant(
        self, tenant_id: str
    ) -> List[Dict[str, Any]]:
        """Retrieve all certifications for a tenant using search_after pagination.

        Fetches certifications across all statuses (valid, expiring_soon,
        expired) for the fleet dashboard view.
        """
        all_certs: List[Dict[str, Any]] = []
        search_after: Optional[list] = None

        while True:
            base_query: Dict[str, Any] = {
                "query": {
                    "bool": {
                        "must": [{"match_all": {}}]
                    }
                },
                "size": _MAX_PAGE_LIMIT,
                "sort": [
                    {"expiry_date": {"order": "asc"}},
                    {"cert_id": {"order": "asc"}},
                ],
            }

            if search_after is not None:
                base_query["search_after"] = search_after

            query = inject_tenant_filter(base_query, tenant_id)

            response = await self._es.search_documents(
                ASSET_CERTIFICATIONS_INDEX, query, size=_MAX_PAGE_LIMIT
            )

            hits = response["hits"]["hits"]
            if not hits:
                break

            for hit in hits:
                all_certs.append(hit["_source"])

            # Set up search_after for next page
            last_sort = hits[-1].get("sort")
            if last_sort:
                search_after = last_sort
            else:
                break

            # If we got fewer than the page size, we're done
            if len(hits) < _MAX_PAGE_LIMIT:
                break

        return all_certs

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _serialize_cert(cert: AssetCertification) -> Dict[str, Any]:
        """Serialize an AssetCertification model to an ES-compatible dict."""
        return {
            "cert_id": cert.cert_id,
            "tenant_id": cert.tenant_id,
            "asset_id": cert.asset_id,
            "certification_type": cert.certification_type,
            "certification_date": cert.certification_date.isoformat(),
            "expiry_date": cert.expiry_date.isoformat(),
            "inspector_name": cert.inspector_name,
            "certificate_number": cert.certificate_number,
            "status": cert.status,
            "created_at": cert.created_at.isoformat(),
            "updated_at": cert.updated_at.isoformat(),
        }

    @staticmethod
    def _parse_date(value: Any) -> Optional[date]:
        """Parse a date from an ISO string or return it if already a date."""
        if isinstance(value, date) and not isinstance(value, datetime):
            return value
        if isinstance(value, datetime):
            return value.date()
        if isinstance(value, str):
            try:
                return date.fromisoformat(value)
            except (ValueError, TypeError):
                return None
        return None
