"""Driver Qualification Service — DQF management and dispatch eligibility.

Implements the ``Driver_Qualification_Service`` described in design §5 of the
Fuel Compliance Backbone spec. This service manages driver qualification files
(CDL, medical card, HAZMAT endorsement, tanker endorsement, drug testing, MVR)
and provides:

* CRUD operations for Driver records in the ``drivers`` ES index.
* ``is_dispatch_eligible()`` — checks whether a driver meets route
  requirements (CDL class, endorsements, status). Implemented in Task 6.3.
* ``check_expiry_alerts()`` — daily cron scanning all drivers for upcoming
  qualification expirations at 60/30/7-day thresholds. Implemented in Task 6.4.
* ``get_dqf_dashboard()`` — tenant-wide compliance dashboard. Implemented
  in Task 6.7.
* ``check_drug_test_overdue()`` — flags drivers with overdue drug tests
  (Req 5.8). Implemented in Task 6.6.

All queries are tenant-scoped via ``inject_tenant_filter`` (Constraint C3).

Validates: Requirement 5.1
"""

from __future__ import annotations

import logging
from datetime import date, datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from compliance.models.driver import Driver, DriverStatus
from compliance.services.compliance_es_mappings import DRIVERS_INDEX
from errors.exceptions import resource_not_found, validation_error
from ops.middleware.tenant_guard import inject_tenant_filter
from services.elasticsearch_service import ElasticsearchService
from services.time_utils import utcnow

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_PAGE_LIMIT = 50
_MAX_PAGE_LIMIT = 200

# Alert thresholds in days (Req 5.2, 5.3, 5.4)
ALERT_THRESHOLD_WARNING_DAYS = 60
ALERT_THRESHOLD_URGENT_DAYS = 30
ALERT_THRESHOLD_CRITICAL_DAYS = 7

# Default drug test interval in days (typically annual per FMCSA)
DEFAULT_DRUG_TEST_INTERVAL_DAYS = 365


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class Alert(BaseModel):
    """Expiry alert generated by check_expiry_alerts."""

    model_config = ConfigDict(extra="forbid")

    driver_id: str
    tenant_id: str
    full_name: str
    qualification_type: str  # cdl | medical_card | hazmat | tanker
    expiry_date: date
    days_until_expiry: int
    severity: str  # warning | urgent | critical
    generated_at: datetime = Field(default_factory=utcnow)


class DriverEligibility(BaseModel):
    """Result of dispatch eligibility check."""

    model_config = ConfigDict(extra="forbid")

    driver_id: str
    eligible: bool
    reasons: List[str] = Field(default_factory=list)


class DQFDashboard(BaseModel):
    """Driver Qualification File compliance dashboard."""

    model_config = ConfigDict(extra="forbid")

    tenant_id: str
    total_drivers: int = 0
    active_drivers: int = 0
    suspended_drivers: int = 0
    expired_drivers: int = 0
    expiring_within_60_days: int = 0
    expiring_within_30_days: int = 0
    expiring_within_7_days: int = 0
    drug_test_overdue: int = 0
    generated_at: datetime = Field(default_factory=utcnow)


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class DriverQualificationService:
    """Service layer for Driver Qualification File management.

    Provides CRUD operations for Driver records and qualification
    compliance checks. Every public method takes ``tenant_id`` as its
    first positional argument and every Elasticsearch query is wrapped
    with ``inject_tenant_filter`` to enforce strict tenant isolation
    (Constraint C3).

    Args:
        es_service: Elasticsearch handle for querying the ``drivers`` index.

    Validates: Requirement 5.1
    """

    def __init__(self, es_service: ElasticsearchService) -> None:
        self._es = es_service

    # ------------------------------------------------------------------
    # Create
    # ------------------------------------------------------------------

    async def create(
        self,
        tenant_id: str,
        *,
        full_name: str,
        cdl_number: str,
        cdl_state: str,
        cdl_class: str,
        cdl_expiry_date: date,
        medical_card_expiry_date: date,
        hazmat_endorsement_expiry_date: Optional[date] = None,
        tanker_endorsement_expiry_date: Optional[date] = None,
        last_drug_test_date: Optional[date] = None,
        last_mvr_date: Optional[date] = None,
        status: str = "active",
        external_refs: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """Create a new Driver record in the drivers index.

        Validates the input via the Driver Pydantic model, assigns a
        server-generated ``driver_id``, and persists to ES.

        Validates: Requirement 5.1
        """
        # Validate via Pydantic model (raises ValueError on invalid input)
        driver = Driver(
            tenant_id=tenant_id,
            full_name=full_name,
            cdl_number=cdl_number,
            cdl_state=cdl_state,
            cdl_class=cdl_class,
            cdl_expiry_date=cdl_expiry_date,
            medical_card_expiry_date=medical_card_expiry_date,
            hazmat_endorsement_expiry_date=hazmat_endorsement_expiry_date,
            tanker_endorsement_expiry_date=tanker_endorsement_expiry_date,
            last_drug_test_date=last_drug_test_date,
            last_mvr_date=last_mvr_date,
            status=status,
            external_refs=external_refs,
        )

        # Serialize for ES — convert dates to ISO strings
        doc = self._serialize_driver(driver)

        await self._es.index_document(DRIVERS_INDEX, driver.driver_id, doc)

        logger.info(
            "Created driver %s (%s) for tenant %s",
            driver.driver_id,
            full_name,
            tenant_id,
        )
        return doc

    # ------------------------------------------------------------------
    # Get
    # ------------------------------------------------------------------

    async def get(self, tenant_id: str, driver_id: str) -> Dict[str, Any]:
        """Retrieve a single Driver by ID, scoped to tenant.

        Raises resource_not_found if the driver does not exist or does
        not belong to the specified tenant.

        Validates: Requirement 5.1, Constraint C3
        """
        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": [
                        {"term": {"driver_id": driver_id}},
                    ]
                }
            },
            "size": 1,
        }
        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            DRIVERS_INDEX, query, size=1
        )

        hits = response["hits"]["hits"]
        if not hits:
            raise resource_not_found(
                f"Driver '{driver_id}' not found",
                details={"driver_id": driver_id},
            )

        return hits[0]["_source"]

    # ------------------------------------------------------------------
    # List
    # ------------------------------------------------------------------

    async def list(
        self,
        tenant_id: str,
        *,
        cursor: Optional[str] = None,
        limit: int = _DEFAULT_PAGE_LIMIT,
        status: Optional[str] = None,
    ) -> Dict[str, Any]:
        """List Drivers for a tenant with cursor/limit pagination.

        Default limit is 50, max 200. Cursor is the ``driver_id`` of
        the last item on the previous page (keyset pagination via
        ``search_after``).

        Validates: Requirement 5.1, Constraint C3
        """
        # Clamp limit
        if limit < 1:
            limit = _DEFAULT_PAGE_LIMIT
        if limit > _MAX_PAGE_LIMIT:
            limit = _MAX_PAGE_LIMIT

        must_clauses: List[Dict[str, Any]] = []
        if status:
            must_clauses.append({"term": {"status": status}})

        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": must_clauses if must_clauses else [{"match_all": {}}],
                }
            },
            "size": limit,
            "sort": [
                {"created_at": {"order": "desc"}},
                {"driver_id": {"order": "asc"}},
            ],
        }

        # Cursor-based pagination using search_after
        if cursor:
            base_query["search_after"] = [cursor, cursor]

        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            DRIVERS_INDEX, query, size=limit
        )

        hits = response["hits"]["hits"]
        items = [hit["_source"] for hit in hits]

        # Determine next cursor
        next_cursor: Optional[str] = None
        if hits and len(hits) == limit:
            last_sort = hits[-1].get("sort")
            if last_sort and len(last_sort) >= 2:
                next_cursor = hits[-1]["_source"]["driver_id"]

        return {
            "items": items,
            "next_cursor": next_cursor,
            "limit": limit,
        }

    # ------------------------------------------------------------------
    # Update
    # ------------------------------------------------------------------

    async def update(
        self,
        tenant_id: str,
        driver_id: str,
        *,
        full_name: Optional[str] = None,
        cdl_number: Optional[str] = None,
        cdl_state: Optional[str] = None,
        cdl_class: Optional[str] = None,
        cdl_expiry_date: Optional[date] = None,
        medical_card_expiry_date: Optional[date] = None,
        hazmat_endorsement_expiry_date: Optional[date] = ...,  # type: ignore[assignment]
        tanker_endorsement_expiry_date: Optional[date] = ...,  # type: ignore[assignment]
        last_drug_test_date: Optional[date] = ...,  # type: ignore[assignment]
        last_mvr_date: Optional[date] = ...,  # type: ignore[assignment]
        status: Optional[str] = None,
        suspension_reason: Optional[str] = ...,  # type: ignore[assignment]
        external_refs: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """Update an existing Driver record.

        Only non-sentinel fields are applied. Uses the sentinel pattern
        (``...``) to distinguish "not provided" from "set to None" for
        optional date fields.

        Validates: Requirement 5.1, Constraint C3
        """
        # Ensure the driver exists and belongs to this tenant
        existing = await self.get(tenant_id, driver_id)

        partial: Dict[str, Any] = {}

        if full_name is not None:
            # Validate via model validator
            stripped = full_name.strip()
            if not stripped:
                raise validation_error(
                    "full_name must not be empty or whitespace",
                    details={"full_name": full_name},
                )
            partial["full_name"] = stripped

        if cdl_number is not None:
            stripped = cdl_number.strip()
            if not stripped:
                raise validation_error(
                    "cdl_number must not be empty or whitespace",
                    details={"cdl_number": cdl_number},
                )
            partial["cdl_number"] = stripped

        if cdl_state is not None:
            # Validate 2-letter uppercase
            stripped = cdl_state.strip()
            if len(stripped) != 2 or not stripped.isalpha() or not stripped.isupper():
                raise validation_error(
                    "cdl_state must be exactly 2 uppercase letters",
                    details={"cdl_state": cdl_state},
                )
            partial["cdl_state"] = stripped

        if cdl_class is not None:
            if cdl_class not in ("A", "B", "C"):
                raise validation_error(
                    "cdl_class must be A, B, or C",
                    details={"cdl_class": cdl_class},
                )
            partial["cdl_class"] = cdl_class

        if cdl_expiry_date is not None:
            partial["cdl_expiry_date"] = cdl_expiry_date.isoformat()

        if medical_card_expiry_date is not None:
            partial["medical_card_expiry_date"] = medical_card_expiry_date.isoformat()

        # Sentinel-guarded optional date fields
        if hazmat_endorsement_expiry_date is not ...:
            partial["hazmat_endorsement_expiry_date"] = (
                hazmat_endorsement_expiry_date.isoformat()
                if hazmat_endorsement_expiry_date is not None
                else None
            )

        if tanker_endorsement_expiry_date is not ...:
            partial["tanker_endorsement_expiry_date"] = (
                tanker_endorsement_expiry_date.isoformat()
                if tanker_endorsement_expiry_date is not None
                else None
            )

        if last_drug_test_date is not ...:
            partial["last_drug_test_date"] = (
                last_drug_test_date.isoformat()
                if last_drug_test_date is not None
                else None
            )

        if last_mvr_date is not ...:
            partial["last_mvr_date"] = (
                last_mvr_date.isoformat()
                if last_mvr_date is not None
                else None
            )

        if status is not None:
            if status not in ("active", "suspended", "expired"):
                raise validation_error(
                    "status must be active, suspended, or expired",
                    details={"status": status},
                )
            partial["status"] = status

        if suspension_reason is not ...:
            partial["suspension_reason"] = (
                suspension_reason.strip() if suspension_reason else None
            )

        if external_refs is not None:
            partial["external_refs"] = external_refs

        if not partial:
            return existing

        partial["updated_at"] = utcnow().isoformat()

        await self._es.update_document(DRIVERS_INDEX, driver_id, partial)

        merged = {**existing, **partial}
        logger.info(
            "Updated driver %s for tenant %s",
            driver_id,
            tenant_id,
        )
        return merged

    # ------------------------------------------------------------------
    # Dispatch eligibility (Task 6.3)
    # ------------------------------------------------------------------

    async def is_dispatch_eligible(
        self,
        tenant_id: str,
        driver_id: str,
        route_requirements: Optional[Dict[str, Any]] = None,
    ) -> DriverEligibility:
        """Check whether a driver is eligible for dispatch.

        Evaluates CDL class, endorsement validity, medical card status,
        and driver status against the route requirements. A suspended or
        expired driver is never eligible.

        Checks performed (in order):
        1. Driver status — suspended or expired → ineligible (Req 5.5)
        2. CDL expiry — expired CDL → ineligible
        3. Medical card expiry — expired medical card → ineligible
        4. HAZMAT endorsement — if route requires HAZMAT, driver must
           have a valid (non-expired) HAZMAT endorsement (Req 5.6)
        5. Tanker endorsement — if route requires tanker, driver must
           have a valid (non-expired) tanker endorsement (Req 5.7)
        6. CDL class — if route specifies min_cdl_class, driver's CDL
           class must meet or exceed the requirement (A > B > C)

        Args:
            tenant_id: Tenant scope for the query.
            driver_id: The driver to evaluate.
            route_requirements: Optional dict with keys:
                - requires_hazmat (bool): Route carries HAZMAT products.
                - requires_tanker (bool): Route uses cargo tank vehicles.
                - min_cdl_class (str): Minimum CDL class required ("A", "B", "C").

        Returns:
            DriverEligibility with eligible=True/False and reasons list.

        Validates: Requirements 5.5, 5.6, 5.7
        """
        driver = await self.get(tenant_id, driver_id)
        reasons: List[str] = []
        today = date.today()

        if route_requirements is None:
            route_requirements = {}

        # 1. Check driver status (Req 5.5)
        status = driver.get("status", "active")
        if status != "active":
            reasons.append(
                f"Driver status is '{status}', must be 'active'"
            )

        # 2. Check CDL expiry
        cdl_expiry_raw = driver.get("cdl_expiry_date")
        if cdl_expiry_raw:
            cdl_expiry = self._parse_date(cdl_expiry_raw)
            if cdl_expiry and cdl_expiry < today:
                reasons.append(
                    f"CDL expired on {cdl_expiry.isoformat()}"
                )

        # 3. Check medical card expiry
        medical_expiry_raw = driver.get("medical_card_expiry_date")
        if medical_expiry_raw:
            medical_expiry = self._parse_date(medical_expiry_raw)
            if medical_expiry and medical_expiry < today:
                reasons.append(
                    f"Medical card expired on {medical_expiry.isoformat()}"
                )

        # 4. Check HAZMAT endorsement (Req 5.6)
        if route_requirements.get("requires_hazmat"):
            hazmat_expiry_raw = driver.get("hazmat_endorsement_expiry_date")
            if not hazmat_expiry_raw:
                reasons.append(
                    "Route requires HAZMAT endorsement but driver has none"
                )
            else:
                hazmat_expiry = self._parse_date(hazmat_expiry_raw)
                if hazmat_expiry and hazmat_expiry < today:
                    reasons.append(
                        f"HAZMAT endorsement expired on {hazmat_expiry.isoformat()}"
                    )

        # 5. Check tanker endorsement (Req 5.7)
        if route_requirements.get("requires_tanker"):
            tanker_expiry_raw = driver.get("tanker_endorsement_expiry_date")
            if not tanker_expiry_raw:
                reasons.append(
                    "Route requires tanker endorsement but driver has none"
                )
            else:
                tanker_expiry = self._parse_date(tanker_expiry_raw)
                if tanker_expiry and tanker_expiry < today:
                    reasons.append(
                        f"Tanker endorsement expired on {tanker_expiry.isoformat()}"
                    )

        # 6. Check CDL class meets minimum requirement
        min_cdl_class = route_requirements.get("min_cdl_class")
        if min_cdl_class:
            driver_cdl_class = driver.get("cdl_class", "C")
            if not self._cdl_class_meets_minimum(driver_cdl_class, min_cdl_class):
                reasons.append(
                    f"Driver CDL class '{driver_cdl_class}' does not meet "
                    f"minimum requirement '{min_cdl_class}'"
                )

        eligible = len(reasons) == 0
        return DriverEligibility(
            driver_id=driver_id,
            eligible=eligible,
            reasons=reasons,
        )

    @staticmethod
    def _parse_date(value: Any) -> Optional[date]:
        """Parse a date from an ISO string or return it if already a date."""
        if isinstance(value, date) and not isinstance(value, datetime):
            return value
        if isinstance(value, datetime):
            return value.date()
        if isinstance(value, str):
            try:
                return date.fromisoformat(value)
            except (ValueError, TypeError):
                return None
        return None

    @staticmethod
    def _cdl_class_meets_minimum(driver_class: str, min_class: str) -> bool:
        """Check if driver's CDL class meets or exceeds the minimum.

        CDL class hierarchy: A > B > C.
        A driver with class A can drive anything requiring A, B, or C.
        A driver with class B can drive B or C but not A.
        A driver with class C can only drive C.
        """
        hierarchy = {"A": 3, "B": 2, "C": 1}
        driver_rank = hierarchy.get(driver_class, 0)
        min_rank = hierarchy.get(min_class, 0)
        return driver_rank >= min_rank

    # ------------------------------------------------------------------
    # Expiry alerts (Task 6.4)
    # ------------------------------------------------------------------

    # Qualification fields to check and their human-readable type names
    _QUALIFICATION_FIELDS = [
        ("cdl_expiry_date", "cdl"),
        ("medical_card_expiry_date", "medical_card"),
        ("hazmat_endorsement_expiry_date", "hazmat"),
        ("tanker_endorsement_expiry_date", "tanker"),
    ]

    async def check_expiry_alerts(self, tenant_id: str) -> List[Alert]:
        """Scan all active drivers for upcoming qualification expirations.

        Queries all active drivers for the tenant and checks each
        qualification date field (CDL, medical card, HAZMAT endorsement,
        tanker endorsement). For each field within 60 days of today,
        generates an Alert with the appropriate severity:

        - ≤7 days  → "critical" (Req 5.4)
        - ≤30 days → "urgent"   (Req 5.3)
        - ≤60 days → "warning"  (Req 5.2)

        Fields that are None/null (e.g., driver without HAZMAT endorsement)
        are skipped.

        Note: Auto-suspend at 7-day threshold is handled by
        ``auto_suspend_expired_drivers()`` (Task 6.5), which should be
        called after this method in the daily cron flow.

        Validates: Requirements 5.2, 5.3, 5.4
        """
        alerts: List[Alert] = []
        today = date.today()

        # Query all active drivers for this tenant
        drivers = await self._get_all_active_drivers(tenant_id)

        for driver_doc in drivers:
            driver_id = driver_doc.get("driver_id", "")
            full_name = driver_doc.get("full_name", "")

            for field_name, qualification_type in self._QUALIFICATION_FIELDS:
                expiry_raw = driver_doc.get(field_name)
                if expiry_raw is None:
                    # Skip fields that are not set (e.g., no HAZMAT endorsement)
                    continue

                expiry_date = self._parse_date(expiry_raw)
                if expiry_date is None:
                    continue

                days_until_expiry = (expiry_date - today).days

                # Only generate alerts for dates within 60 days
                if days_until_expiry > ALERT_THRESHOLD_WARNING_DAYS:
                    continue

                # Determine severity based on thresholds (most severe first)
                if days_until_expiry <= ALERT_THRESHOLD_CRITICAL_DAYS:
                    severity = "critical"
                elif days_until_expiry <= ALERT_THRESHOLD_URGENT_DAYS:
                    severity = "urgent"
                else:
                    severity = "warning"

                alert = Alert(
                    driver_id=driver_id,
                    tenant_id=tenant_id,
                    full_name=full_name,
                    qualification_type=qualification_type,
                    expiry_date=expiry_date,
                    days_until_expiry=days_until_expiry,
                    severity=severity,
                )
                alerts.append(alert)

        logger.info(
            "Generated %d expiry alerts for tenant %s",
            len(alerts),
            tenant_id,
        )
        return alerts

    async def _get_all_active_drivers(self, tenant_id: str) -> List[Dict[str, Any]]:
        """Retrieve all active drivers for a tenant using scroll-style pagination.

        Uses search_after pagination to fetch all active drivers without
        hitting the default page size limit.
        """
        all_drivers: List[Dict[str, Any]] = []
        search_after: Optional[list] = None

        while True:
            base_query: Dict[str, Any] = {
                "query": {
                    "bool": {
                        "must": [
                            {"term": {"status": "active"}},
                        ]
                    }
                },
                "size": _MAX_PAGE_LIMIT,
                "sort": [
                    {"driver_id": {"order": "asc"}},
                ],
            }

            if search_after is not None:
                base_query["search_after"] = search_after

            query = inject_tenant_filter(base_query, tenant_id)

            response = await self._es.search_documents(
                DRIVERS_INDEX, query, size=_MAX_PAGE_LIMIT
            )

            hits = response["hits"]["hits"]
            if not hits:
                break

            for hit in hits:
                all_drivers.append(hit["_source"])

            # Set up search_after for next page
            last_sort = hits[-1].get("sort")
            if last_sort:
                search_after = last_sort
            else:
                break

            # If we got fewer than the page size, we're done
            if len(hits) < _MAX_PAGE_LIMIT:
                break

        return all_drivers

    # ------------------------------------------------------------------
    # Auto-suspend at 7-day threshold (Task 6.5)
    # ------------------------------------------------------------------

    async def auto_suspend_expired_drivers(self, tenant_id: str) -> List[Dict[str, Any]]:
        """Auto-suspend drivers with qualifications expiring within 7 days.

        Scans all active drivers for the tenant and transitions any driver
        whose qualification expiry date is within 7 days (or already past)
        to ``suspended`` status. The ``suspension_reason`` field is set to
        indicate which qualification triggered the suspension and how many
        days remain.

        Only drivers with status ``active`` are evaluated — already
        suspended or expired drivers are skipped to avoid redundant updates.

        This method is designed to be called as part of the daily cron flow,
        typically after ``check_expiry_alerts()`` or integrated into the
        same scheduler task.

        Returns:
            A list of dicts describing each suspension action taken, with
            keys: driver_id, full_name, qualification_type, days_until_expiry,
            suspension_reason.

        Validates: Requirement 5.4
        """
        suspensions: List[Dict[str, Any]] = []
        today = date.today()

        # Query all active drivers for this tenant
        drivers = await self._get_all_active_drivers(tenant_id)

        for driver_doc in drivers:
            driver_id = driver_doc.get("driver_id", "")
            full_name = driver_doc.get("full_name", "")
            status = driver_doc.get("status", "active")

            # Only suspend active drivers (skip already suspended/expired)
            if status != "active":
                continue

            # Check each qualification field for ≤7 days
            for field_name, qualification_type in self._QUALIFICATION_FIELDS:
                expiry_raw = driver_doc.get(field_name)
                if expiry_raw is None:
                    continue

                expiry_date = self._parse_date(expiry_raw)
                if expiry_date is None:
                    continue

                days_until_expiry = (expiry_date - today).days

                if days_until_expiry <= ALERT_THRESHOLD_CRITICAL_DAYS:
                    # Build a human-readable suspension reason
                    qual_label = qualification_type.replace("_", " ").upper()
                    if days_until_expiry < 0:
                        suspension_reason = (
                            f"{qual_label} expired {abs(days_until_expiry)} days ago"
                        )
                    elif days_until_expiry == 0:
                        suspension_reason = f"{qual_label} expires today"
                    else:
                        suspension_reason = (
                            f"{qual_label} expiring in {days_until_expiry} days"
                        )

                    # Transition driver to suspended
                    await self.update(
                        tenant_id,
                        driver_id,
                        status="suspended",
                        suspension_reason=suspension_reason,
                    )

                    suspensions.append({
                        "driver_id": driver_id,
                        "full_name": full_name,
                        "qualification_type": qualification_type,
                        "days_until_expiry": days_until_expiry,
                        "suspension_reason": suspension_reason,
                    })

                    logger.warning(
                        "Auto-suspended driver %s (%s) for tenant %s: %s",
                        driver_id,
                        full_name,
                        tenant_id,
                        suspension_reason,
                    )

                    # Once suspended, no need to check remaining fields
                    # for this driver
                    break

        logger.info(
            "Auto-suspend scan complete for tenant %s: %d drivers suspended",
            tenant_id,
            len(suspensions),
        )
        return suspensions

    # ------------------------------------------------------------------
    # Drug test overdue check (Task 6.6)
    # ------------------------------------------------------------------

    async def check_drug_test_overdue(
        self,
        tenant_id: str,
        interval_days: int = DEFAULT_DRUG_TEST_INTERVAL_DAYS,
    ) -> List[Dict[str, Any]]:
        """Flag drivers with last_drug_test_date older than the configured interval.

        Queries all active drivers for the tenant and checks each driver's
        ``last_drug_test_date``. A driver is flagged as overdue if:
        - ``last_drug_test_date`` is None (never tested), OR
        - ``last_drug_test_date`` is more than ``interval_days`` ago from today.

        Args:
            tenant_id: Tenant scope for the query.
            interval_days: Maximum number of days since last drug test before
                flagging as overdue. Defaults to 365 (annual per FMCSA).

        Returns:
            A list of dicts for each overdue driver with keys:
            driver_id, full_name, last_drug_test_date, days_overdue.

        Validates: Requirement 5.8
        """
        overdue_drivers: List[Dict[str, Any]] = []
        today = date.today()

        # Query all active drivers for this tenant
        drivers = await self._get_all_active_drivers(tenant_id)

        for driver_doc in drivers:
            driver_id = driver_doc.get("driver_id", "")
            full_name = driver_doc.get("full_name", "")
            last_drug_test_raw = driver_doc.get("last_drug_test_date")

            if last_drug_test_raw is None:
                # Never tested — flag as overdue with days_overdue = None
                overdue_drivers.append({
                    "driver_id": driver_id,
                    "full_name": full_name,
                    "last_drug_test_date": None,
                    "days_overdue": None,
                })
                continue

            last_drug_test_date = self._parse_date(last_drug_test_raw)
            if last_drug_test_date is None:
                # Unparseable date — treat as never tested
                overdue_drivers.append({
                    "driver_id": driver_id,
                    "full_name": full_name,
                    "last_drug_test_date": None,
                    "days_overdue": None,
                })
                continue

            days_since_test = (today - last_drug_test_date).days

            if days_since_test > interval_days:
                days_overdue = days_since_test - interval_days
                overdue_drivers.append({
                    "driver_id": driver_id,
                    "full_name": full_name,
                    "last_drug_test_date": last_drug_test_date.isoformat(),
                    "days_overdue": days_overdue,
                })

        logger.info(
            "Drug test overdue check for tenant %s: %d drivers flagged",
            tenant_id,
            len(overdue_drivers),
        )
        return overdue_drivers

    # ------------------------------------------------------------------
    # DQF Dashboard (Task 6.7)
    # ------------------------------------------------------------------

    async def get_dqf_dashboard(self, tenant_id: str) -> DQFDashboard:
        """Generate a tenant-wide DQF compliance dashboard.

        Queries ALL drivers for the tenant (active, suspended, expired)
        and aggregates:
        - total_drivers, active_drivers, suspended_drivers, expired_drivers
        - expiring_within_60_days, expiring_within_30_days, expiring_within_7_days
          (unique driver counts — a driver is counted once even if multiple
          qualifications are expiring)
        - drug_test_overdue (active drivers with overdue drug tests)

        The expiry threshold counts only consider active drivers, since
        suspended/expired drivers are already flagged.

        Validates: Requirement 5.9
        """
        today = date.today()

        # Query ALL drivers for this tenant (all statuses)
        all_drivers = await self._get_all_drivers(tenant_id)

        total_drivers = len(all_drivers)
        active_drivers = 0
        suspended_drivers = 0
        expired_drivers = 0

        # Sets to track unique drivers expiring within thresholds
        expiring_60: set = set()
        expiring_30: set = set()
        expiring_7: set = set()
        drug_test_overdue_count = 0

        for driver_doc in all_drivers:
            driver_id = driver_doc.get("driver_id", "")
            status = driver_doc.get("status", "active")

            # Count by status
            if status == "active":
                active_drivers += 1
            elif status == "suspended":
                suspended_drivers += 1
            elif status == "expired":
                expired_drivers += 1

            # Only check expiry thresholds for active drivers
            if status == "active":
                # Check qualification expiry dates
                for field_name, _ in self._QUALIFICATION_FIELDS:
                    expiry_raw = driver_doc.get(field_name)
                    if expiry_raw is None:
                        continue

                    expiry_date = self._parse_date(expiry_raw)
                    if expiry_date is None:
                        continue

                    days_until_expiry = (expiry_date - today).days

                    if days_until_expiry <= ALERT_THRESHOLD_WARNING_DAYS:
                        expiring_60.add(driver_id)
                    if days_until_expiry <= ALERT_THRESHOLD_URGENT_DAYS:
                        expiring_30.add(driver_id)
                    if days_until_expiry <= ALERT_THRESHOLD_CRITICAL_DAYS:
                        expiring_7.add(driver_id)

                # Check drug test overdue (same logic as check_drug_test_overdue)
                last_drug_test_raw = driver_doc.get("last_drug_test_date")
                if last_drug_test_raw is None:
                    # Never tested — overdue
                    drug_test_overdue_count += 1
                else:
                    last_drug_test_date = self._parse_date(last_drug_test_raw)
                    if last_drug_test_date is None:
                        # Unparseable — treat as overdue
                        drug_test_overdue_count += 1
                    else:
                        days_since_test = (today - last_drug_test_date).days
                        if days_since_test > DEFAULT_DRUG_TEST_INTERVAL_DAYS:
                            drug_test_overdue_count += 1

        dashboard = DQFDashboard(
            tenant_id=tenant_id,
            total_drivers=total_drivers,
            active_drivers=active_drivers,
            suspended_drivers=suspended_drivers,
            expired_drivers=expired_drivers,
            expiring_within_60_days=len(expiring_60),
            expiring_within_30_days=len(expiring_30),
            expiring_within_7_days=len(expiring_7),
            drug_test_overdue=drug_test_overdue_count,
        )

        logger.info(
            "Generated DQF dashboard for tenant %s: %d total, %d active, "
            "%d suspended, %d expired, %d expiring ≤60d, %d drug test overdue",
            tenant_id,
            total_drivers,
            active_drivers,
            suspended_drivers,
            expired_drivers,
            len(expiring_60),
            drug_test_overdue_count,
        )
        return dashboard

    async def _get_all_drivers(self, tenant_id: str) -> List[Dict[str, Any]]:
        """Retrieve ALL drivers for a tenant (all statuses) using scroll-style pagination.

        Unlike ``_get_all_active_drivers``, this method does not filter by
        status, returning active, suspended, and expired drivers.
        """
        all_drivers: List[Dict[str, Any]] = []
        search_after: Optional[list] = None

        while True:
            base_query: Dict[str, Any] = {
                "query": {
                    "bool": {
                        "must": [
                            {"match_all": {}},
                        ]
                    }
                },
                "size": _MAX_PAGE_LIMIT,
                "sort": [
                    {"driver_id": {"order": "asc"}},
                ],
            }

            if search_after is not None:
                base_query["search_after"] = search_after

            query = inject_tenant_filter(base_query, tenant_id)

            response = await self._es.search_documents(
                DRIVERS_INDEX, query, size=_MAX_PAGE_LIMIT
            )

            hits = response["hits"]["hits"]
            if not hits:
                break

            for hit in hits:
                all_drivers.append(hit["_source"])

            # Set up search_after for next page
            last_sort = hits[-1].get("sort")
            if last_sort:
                search_after = last_sort
            else:
                break

            # If we got fewer than the page size, we're done
            if len(hits) < _MAX_PAGE_LIMIT:
                break

        return all_drivers

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _serialize_driver(driver: Driver) -> Dict[str, Any]:
        """Serialize a Driver model to an ES-compatible dict.

        Converts date/datetime fields to ISO format strings for ES
        indexing.
        """
        doc: Dict[str, Any] = {
            "driver_id": driver.driver_id,
            "tenant_id": driver.tenant_id,
            "full_name": driver.full_name,
            "cdl_number": driver.cdl_number,
            "cdl_state": driver.cdl_state,
            "cdl_class": driver.cdl_class,
            "cdl_expiry_date": driver.cdl_expiry_date.isoformat(),
            "medical_card_expiry_date": driver.medical_card_expiry_date.isoformat(),
            "hazmat_endorsement_expiry_date": (
                driver.hazmat_endorsement_expiry_date.isoformat()
                if driver.hazmat_endorsement_expiry_date
                else None
            ),
            "tanker_endorsement_expiry_date": (
                driver.tanker_endorsement_expiry_date.isoformat()
                if driver.tanker_endorsement_expiry_date
                else None
            ),
            "last_drug_test_date": (
                driver.last_drug_test_date.isoformat()
                if driver.last_drug_test_date
                else None
            ),
            "last_mvr_date": (
                driver.last_mvr_date.isoformat()
                if driver.last_mvr_date
                else None
            ),
            "status": driver.status,
            "suspension_reason": driver.suspension_reason,
            "external_refs": driver.external_refs,
            "created_at": driver.created_at.isoformat(),
            "updated_at": driver.updated_at.isoformat(),
        }
        return doc
