"""Meter Audit Service — Meter registry, ticket-to-invoice linking, and audit trail.

Implements the ``Meter_Audit_Service`` described in design §8 of the
Fuel Compliance Backbone spec. This service manages meter registration
records and provides:

* CRUD operations for MeterRegistration records in the ``meter_registry``
  ES index.
* ``register_meter()`` — creates a new meter in the registry (Task 10.2).
* ``get_meter()`` / ``list_meters()`` — tenant-scoped retrieval.
* ``link_ticket_to_invoice()`` — records the immutable association between
  a meter ticket, delivery, and invoice (Task 10.3).
* ``check_calibration_alerts()`` — daily cron scanning all meters for
  upcoming calibration expirations at 30-day threshold (Task 10.4).
* ``get_meter_audit_trail()`` — per-meter audit trail (Task 10.5).
* ``flag_variance()`` — flags deliveries where meter vs POD > 1% (Task 10.6).

All queries are tenant-scoped via ``inject_tenant_filter`` (Constraint C3).

Validates: Requirement 8.1
"""

from __future__ import annotations

import logging
from datetime import date, datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from compliance.models.meter import MeterRegistration, MeterAuditEntry
from compliance.services.compliance_es_mappings import (
    METER_REGISTRY_INDEX,
    METER_AUDIT_TRAIL_INDEX,
)
from errors.exceptions import resource_not_found, validation_error
from ops.middleware.tenant_guard import inject_tenant_filter
from services.elasticsearch_service import ElasticsearchService
from services.time_utils import utcnow
from services.keyset_pagination import (
    next_cursor_from_hits,
    search_after_for_cursor,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_PAGE_LIMIT = 50
_MAX_PAGE_LIMIT = 200

# Calibration alert threshold in days (Req 8.4)
CALIBRATION_ALERT_THRESHOLD_DAYS = 30

# Variance threshold percentage (Req 8.7)
VARIANCE_THRESHOLD_PERCENT = 1.0


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------


class CalibrationAlert(BaseModel):
    """Calibration expiry alert generated by check_calibration_alerts."""

    model_config = ConfigDict(extra="forbid")

    meter_id: str
    tenant_id: str
    meter_number: str
    truck_id: str
    calibration_expiry_date: date
    days_until_expiry: int
    severity: str  # warning | critical
    generated_at: datetime = Field(default_factory=utcnow)


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class MeterAuditService:
    """Service layer for Meter Audit management.

    Provides CRUD operations for MeterRegistration records, ticket-to-invoice
    linking, calibration alert scanning, per-meter audit trail retrieval,
    and variance flagging. Every public method takes ``tenant_id`` as its
    first positional argument and every Elasticsearch query is wrapped
    with ``inject_tenant_filter`` to enforce strict tenant isolation
    (Constraint C3).

    Args:
        es_service: Elasticsearch handle for querying the ``meter_registry``
            and ``meter_audit_trail`` indices.

    Validates: Requirement 8.1
    """

    def __init__(self, es_service: ElasticsearchService) -> None:
        self._es = es_service

    # ------------------------------------------------------------------
    # Register meter (Task 10.2)
    # ------------------------------------------------------------------

    async def register_meter(
        self,
        tenant_id: str,
        *,
        meter_number: str,
        truck_id: str,
        calibration_certificate_number: str,
        calibration_date: date,
        calibration_expiry_date: date,
        weights_measures_authority: str,
        status: str = "active",
    ) -> Dict[str, Any]:
        """Register a new meter in the meter registry.

        Validates the input via the MeterRegistration Pydantic model,
        assigns a server-generated ``meter_id``, and persists to ES.

        Validates: Requirement 8.1, 8.3
        """
        meter = MeterRegistration(
            tenant_id=tenant_id,
            meter_number=meter_number,
            truck_id=truck_id,
            calibration_certificate_number=calibration_certificate_number,
            calibration_date=calibration_date,
            calibration_expiry_date=calibration_expiry_date,
            weights_measures_authority=weights_measures_authority,
            status=status,
        )

        doc = self._serialize_meter(meter)

        await self._es.index_document(METER_REGISTRY_INDEX, meter.meter_id, doc)

        logger.info(
            "Registered meter %s (number=%s, truck=%s) for tenant %s",
            meter.meter_id,
            meter_number,
            truck_id,
            tenant_id,
        )
        return doc

    # ------------------------------------------------------------------
    # Get meter
    # ------------------------------------------------------------------

    async def get_meter(self, tenant_id: str, meter_id: str) -> Dict[str, Any]:
        """Retrieve a single MeterRegistration by ID, scoped to tenant.

        Raises resource_not_found if the meter does not exist or does
        not belong to the specified tenant.

        Validates: Requirement 8.3, Constraint C3
        """
        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": [
                        {"term": {"meter_id": meter_id}},
                    ]
                }
            },
            "size": 1,
        }
        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            METER_REGISTRY_INDEX, query, size=1
        )

        hits = response["hits"]["hits"]
        if not hits:
            raise resource_not_found(
                f"Meter '{meter_id}' not found",
                details={"meter_id": meter_id},
            )

        return hits[0]["_source"]

    # ------------------------------------------------------------------
    # List meters
    # ------------------------------------------------------------------

    async def list_meters(
        self,
        tenant_id: str,
        *,
        truck_id: Optional[str] = None,
        status: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: int = _DEFAULT_PAGE_LIMIT,
    ) -> Dict[str, Any]:
        """List MeterRegistrations for a tenant with cursor/limit pagination.

        Supports optional filtering by truck_id and status. Default limit
        is 50, max 200. Cursor is the ``meter_id`` of the last item on
        the previous page (keyset pagination via ``search_after``).

        Validates: Requirement 8.3, Constraint C3
        """
        if limit < 1:
            limit = _DEFAULT_PAGE_LIMIT
        if limit > _MAX_PAGE_LIMIT:
            limit = _MAX_PAGE_LIMIT

        must_clauses: List[Dict[str, Any]] = []
        if truck_id:
            must_clauses.append({"term": {"truck_id": truck_id}})
        if status:
            must_clauses.append({"term": {"status": status}})

        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": must_clauses if must_clauses else [{"match_all": {}}],
                }
            },
            "size": limit,
            "sort": [
                {"created_at": {"order": "desc"}},
                {"meter_id": {"order": "asc"}},
            ],
        }

        if cursor:
            base_query["search_after"] = await search_after_for_cursor(
                self._es, METER_REGISTRY_INDEX, cursor, base_query["sort"]
            )

        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            METER_REGISTRY_INDEX, query, size=limit
        )

        hits = response["hits"]["hits"]
        items = [hit["_source"] for hit in hits]

        next_cursor = next_cursor_from_hits(
            hits, limit, id_field="meter_id"
        )

        return {
            "items": items,
            "next_cursor": next_cursor,
            "limit": limit,
        }

    # ------------------------------------------------------------------
    # Link ticket to invoice (Task 10.3 — skeleton)
    # ------------------------------------------------------------------

    async def link_ticket_to_invoice(
        self,
        tenant_id: str,
        *,
        meter_id: str,
        meter_ticket_id: str,
        delivery_id: str,
        invoice_id: str,
        gross_gallons: float,
        timestamp: datetime,
    ) -> Dict[str, Any]:
        """Record the immutable association between meter ticket, delivery, and invoice.

        Creates a MeterAuditEntry linking the meter_ticket_id, invoice_id,
        and delivery_id as an immutable audit record.

        Validates: Requirement 8.2
        """
        audit_entry = MeterAuditEntry(
            tenant_id=tenant_id,
            meter_id=meter_id,
            meter_ticket_id=meter_ticket_id,
            delivery_id=delivery_id,
            invoice_id=invoice_id,
            gross_gallons=gross_gallons,
            timestamp=timestamp,
        )

        doc = self._serialize_audit_entry(audit_entry)

        await self._es.index_document(
            METER_AUDIT_TRAIL_INDEX, audit_entry.audit_id, doc
        )

        logger.info(
            "Linked meter ticket %s to invoice %s (delivery=%s) for tenant %s",
            meter_ticket_id,
            invoice_id,
            delivery_id,
            tenant_id,
        )
        return doc

    # ------------------------------------------------------------------
    # Check calibration alerts (Task 10.4 — skeleton)
    # ------------------------------------------------------------------

    async def check_calibration_alerts(self, tenant_id: str) -> List[CalibrationAlert]:
        """Scan all active meters for upcoming calibration expirations.

        Queries all active meters for the tenant and checks each meter's
        calibration_expiry_date against today. For each meter within 30
        days of expiry, generates a CalibrationAlert:

        - ≤7 days (or already past) → "critical"
        - ≤30 days → "warning" (Req 8.4)

        Validates: Requirement 8.4
        """
        alerts: List[CalibrationAlert] = []
        today = date.today()

        meters = await self._get_all_active_meters(tenant_id)

        for meter_doc in meters:
            meter_id = meter_doc.get("meter_id", "")
            meter_number = meter_doc.get("meter_number", "")
            truck_id = meter_doc.get("truck_id", "")
            expiry_raw = meter_doc.get("calibration_expiry_date")

            if expiry_raw is None:
                continue

            expiry_date = self._parse_date(expiry_raw)
            if expiry_date is None:
                continue

            days_until_expiry = (expiry_date - today).days

            if days_until_expiry > CALIBRATION_ALERT_THRESHOLD_DAYS:
                continue

            # Determine severity
            if days_until_expiry <= 7:
                severity = "critical"
            else:
                severity = "warning"

            alert = CalibrationAlert(
                meter_id=meter_id,
                tenant_id=tenant_id,
                meter_number=meter_number,
                truck_id=truck_id,
                calibration_expiry_date=expiry_date,
                days_until_expiry=days_until_expiry,
                severity=severity,
            )
            alerts.append(alert)

        logger.info(
            "Generated %d calibration alerts for tenant %s",
            len(alerts),
            tenant_id,
        )
        return alerts

    # ------------------------------------------------------------------
    # Get meter audit trail (Task 10.5 — skeleton)
    # ------------------------------------------------------------------

    async def get_meter_audit_trail(
        self,
        tenant_id: str,
        meter_id: str,
        *,
        cursor: Optional[str] = None,
        limit: int = _DEFAULT_PAGE_LIMIT,
    ) -> Dict[str, Any]:
        """Retrieve the per-meter audit trail.

        Returns all audit entries for a specific meter, ordered by
        timestamp descending (most recent first).

        Validates: Requirement 8.6
        """
        if limit < 1:
            limit = _DEFAULT_PAGE_LIMIT
        if limit > _MAX_PAGE_LIMIT:
            limit = _MAX_PAGE_LIMIT

        base_query: Dict[str, Any] = {
            "query": {
                "bool": {
                    "must": [
                        {"term": {"meter_id": meter_id}},
                    ]
                }
            },
            "size": limit,
            "sort": [
                {"created_at": {"order": "desc"}},
                {"audit_id": {"order": "asc"}},
            ],
        }

        if cursor:
            base_query["search_after"] = await search_after_for_cursor(
                self._es, METER_AUDIT_TRAIL_INDEX, cursor, base_query["sort"]
            )

        query = inject_tenant_filter(base_query, tenant_id)

        response = await self._es.search_documents(
            METER_AUDIT_TRAIL_INDEX, query, size=limit
        )

        hits = response["hits"]["hits"]
        items = [hit["_source"] for hit in hits]

        next_cursor = next_cursor_from_hits(
            hits, limit, id_field="audit_id"
        )

        return {
            "items": items,
            "next_cursor": next_cursor,
            "limit": limit,
        }

    # ------------------------------------------------------------------
    # Check meter calibration for delivery (Task 10.6 — Req 8.5)
    # ------------------------------------------------------------------

    async def check_meter_calibration_for_delivery(
        self,
        tenant_id: str,
        *,
        meter_id: str,
        delivery_id: str,
        invoice_id: str,
    ) -> Dict[str, Any]:
        """Check if a delivery was recorded using a meter with expired calibration.

        Looks up the meter's calibration_expiry_date. If the calibration has
        expired (expiry_date < today), flags the invoice with warning code
        ``meter.calibration_expired`` and records an audit trail entry.

        Returns a dict with:
        - flagged: bool — whether the invoice was flagged
        - warning_code: Optional[str] — the warning code if flagged
        - message: Optional[str] — human-readable description if flagged

        Validates: Requirement 8.5
        """
        today = date.today()

        # Look up the meter
        try:
            meter_doc = await self.get_meter(tenant_id, meter_id)
        except Exception:
            # Graceful degradation: if meter not found, don't flag
            logger.warning(
                "Meter %s not found for delivery %s — skipping calibration check",
                meter_id,
                delivery_id,
            )
            return {
                "flagged": False,
                "warning_code": None,
                "message": None,
            }

        # Parse calibration expiry date
        expiry_raw = meter_doc.get("calibration_expiry_date")
        if expiry_raw is None:
            return {
                "flagged": False,
                "warning_code": None,
                "message": None,
            }

        expiry_date = self._parse_date(expiry_raw)
        if expiry_date is None:
            return {
                "flagged": False,
                "warning_code": None,
                "message": None,
            }

        # Check if calibration has expired
        if expiry_date >= today:
            return {
                "flagged": False,
                "warning_code": None,
                "message": None,
            }

        # Calibration is expired — flag the invoice
        warning_code = "meter.calibration_expired"
        message = (
            f"Meter {meter_id} calibration expired on {expiry_date.isoformat()}. "
            f"Delivery {delivery_id} was recorded using an expired meter."
        )

        # Record an audit trail entry for the flagging
        audit_id = f"maudit_{uuid4()}"
        now = utcnow()

        audit_doc: Dict[str, Any] = {
            "audit_id": audit_id,
            "tenant_id": tenant_id,
            "meter_id": meter_id,
            "meter_ticket_id": "",
            "delivery_id": delivery_id,
            "invoice_id": invoice_id,
            "gross_gallons": 0.0,
            "variance_flags": [warning_code],
            "event_type": "calibration_expired_flag",
            "calibration_expiry_date": expiry_date.isoformat(),
            "occurred_at": now.isoformat(),
            "created_at": now.isoformat(),
            "updated_at": now.isoformat(),
        }

        await self._es.index_document(METER_AUDIT_TRAIL_INDEX, audit_id, audit_doc)

        logger.warning(
            "Flagged invoice %s with %s: meter %s calibration expired %s "
            "(delivery=%s, tenant=%s)",
            invoice_id,
            warning_code,
            meter_id,
            expiry_date.isoformat(),
            delivery_id,
            tenant_id,
        )

        return {
            "flagged": True,
            "warning_code": warning_code,
            "message": message,
        }

    # ------------------------------------------------------------------
    # Flag variance (Task 10.6 — skeleton)
    # ------------------------------------------------------------------

    async def flag_variance(
        self,
        tenant_id: str,
        *,
        delivery_id: str,
        meter_id: str,
        meter_gallons: float,
        pod_gallons: float,
    ) -> Optional[Dict[str, Any]]:
        """Flag a delivery if meter vs POD gallons differ by more than 1%.

        Computes the variance percentage between meter_gallons and
        pod_gallons. If the absolute variance exceeds 1%, creates an
        audit trail entry with the ``meter_pod_variance`` flag.

        Returns the audit entry if a variance was flagged, None otherwise.

        Validates: Requirement 8.7
        """
        if pod_gallons == 0:
            logger.warning(
                "Cannot compute variance for delivery %s: pod_gallons is 0",
                delivery_id,
            )
            return None

        variance_pct = abs(meter_gallons - pod_gallons) / pod_gallons * 100.0

        if variance_pct <= VARIANCE_THRESHOLD_PERCENT:
            return None

        # Create an audit trail entry flagging the variance
        audit_id = f"maudit_{uuid4()}"
        now = utcnow()

        doc: Dict[str, Any] = {
            "audit_id": audit_id,
            "tenant_id": tenant_id,
            "meter_id": meter_id,
            "meter_ticket_id": "",
            "delivery_id": delivery_id,
            "invoice_id": None,
            "gross_gallons": meter_gallons,
            "pod_gallons": pod_gallons,
            "variance_pct": round(variance_pct, 4),
            "variance_flags": ["meter_pod_variance"],
            "event_type": "variance_flagged",
            "occurred_at": now.isoformat(),
            "created_at": now.isoformat(),
            "updated_at": now.isoformat(),
        }

        await self._es.index_document(METER_AUDIT_TRAIL_INDEX, audit_id, doc)

        logger.warning(
            "Flagged variance for delivery %s: meter=%.2f, pod=%.2f, "
            "variance=%.4f%% (threshold=%.1f%%) for tenant %s",
            delivery_id,
            meter_gallons,
            pod_gallons,
            variance_pct,
            VARIANCE_THRESHOLD_PERCENT,
            tenant_id,
        )
        return doc

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _get_all_active_meters(self, tenant_id: str) -> List[Dict[str, Any]]:
        """Retrieve all active meters for a tenant using search_after pagination."""
        all_meters: List[Dict[str, Any]] = []
        search_after: Optional[list] = None

        while True:
            base_query: Dict[str, Any] = {
                "query": {
                    "bool": {
                        "must": [
                            {"term": {"status": "active"}},
                        ]
                    }
                },
                "size": _MAX_PAGE_LIMIT,
                "sort": [
                    {"meter_id": {"order": "asc"}},
                ],
            }

            if search_after is not None:
                base_query["search_after"] = search_after

            query = inject_tenant_filter(base_query, tenant_id)

            response = await self._es.search_documents(
                METER_REGISTRY_INDEX, query, size=_MAX_PAGE_LIMIT
            )

            hits = response["hits"]["hits"]
            if not hits:
                break

            for hit in hits:
                all_meters.append(hit["_source"])

            last_sort = hits[-1].get("sort")
            if last_sort:
                search_after = last_sort
            else:
                break

            if len(hits) < _MAX_PAGE_LIMIT:
                break

        return all_meters

    @staticmethod
    def _parse_date(value: Any) -> Optional[date]:
        """Parse a date from an ISO string or return it if already a date."""
        if isinstance(value, date) and not isinstance(value, datetime):
            return value
        if isinstance(value, datetime):
            return value.date()
        if isinstance(value, str):
            try:
                return date.fromisoformat(value)
            except (ValueError, TypeError):
                return None
        return None

    @staticmethod
    def _serialize_meter(meter: MeterRegistration) -> Dict[str, Any]:
        """Serialize a MeterRegistration model to an ES-compatible dict."""
        return {
            "meter_id": meter.meter_id,
            "tenant_id": meter.tenant_id,
            "meter_number": meter.meter_number,
            "truck_id": meter.truck_id,
            "calibration_certificate_number": meter.calibration_certificate_number,
            "calibration_date": meter.calibration_date.isoformat(),
            "calibration_expiry_date": meter.calibration_expiry_date.isoformat(),
            "weights_measures_authority": meter.weights_measures_authority,
            "status": meter.status,
            "created_at": meter.created_at.isoformat(),
            "updated_at": meter.updated_at.isoformat(),
        }

    @staticmethod
    def _serialize_audit_entry(entry: MeterAuditEntry) -> Dict[str, Any]:
        """Serialize a MeterAuditEntry model to an ES-compatible dict."""
        return {
            "audit_id": entry.audit_id,
            "tenant_id": entry.tenant_id,
            "meter_id": entry.meter_id,
            "meter_ticket_id": entry.meter_ticket_id,
            "delivery_id": entry.delivery_id,
            "invoice_id": entry.invoice_id,
            "gross_gallons": entry.gross_gallons,
            "timestamp": entry.timestamp.isoformat(),
            "created_at": entry.created_at.isoformat(),
        }
