#!/usr/bin/env node
/**
 * Design-token generator (UI revamp, design.md §2.2). Node >= 20, no deps.
 *
 *   node scripts/build-tokens.mjs            write the generated files
 *   node scripts/build-tokens.mjs --check    exit 1 if any generated file is stale
 *   node scripts/build-tokens.mjs --with-driver
 *       also generate driver-app/lib/tokens.ts and the marked block in
 *       driver-app/global.css. Off until task 4.1 adopts the tokens in the
 *       driver app, so Phase 1 leaves the driver app untouched.
 *
 * Source of truth: design/tokens.json. Outputs (committed):
 *   runsheet/src/styles/tokens.css   :root variables + Tailwind v4 @theme map
 *   runsheet/src/styles/tokens.ts    typed constants (STATUS, PRODUCT, ...)
 *   driver-app/lib/tokens.ts         (with --with-driver)
 *   driver-app/global.css            block between tokens:start / tokens:end
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const CHECK = args.has("--check");
const WITH_DRIVER = args.has("--with-driver");

const tokens = JSON.parse(readFileSync(join(ROOT, "design/tokens.json"), "utf8"));
const HEADER =
  "Generated by scripts/build-tokens.mjs from design/tokens.json. Do not edit by hand.";

// ── resolution ────────────────────────────────────────────────────────────
function resolve(ref) {
  if (typeof ref !== "string") throw new Error(`Bad token ref ${ref}`);
  if (ref.startsWith("#")) return ref.toLowerCase();
  const [hue, step] = ref.split(".");
  const v = tokens.color[hue]?.[step];
  if (!v) throw new Error(`Unknown colour reference "${ref}"`);
  return v.toLowerCase();
}
const kebab = (s) => s.toLowerCase().replace(/_/g, "-");

const semantic = Object.fromEntries(
  Object.entries(tokens.semantic).map(([k, v]) => [k, resolve(v)]),
);
const status = Object.fromEntries(
  Object.entries(tokens.status).map(([name, s]) => {
    const roles = Object.fromEntries(
      Object.entries(tokens.statusRoles).map(([role, step]) => [
        role,
        resolve(`${s.hue}.${step}`),
      ]),
    );
    return [name, { ...s, strike: Boolean(s.strike), ...roles }];
  }),
);
const products = Object.fromEntries(
  Object.entries(tokens.product).map(([code, p]) => [
    code,
    { ...p, bg: resolve(p.bg), fg: resolve(p.fg), border: resolve(p.border) },
  ]),
);
const identity = tokens.identity.map((ref) => ({ token: ref, hex: resolve(ref) }));
const chart = tokens.chart.map(resolve);

// Legacy aliases kept so Phase 1 does not break untouched pages (§2.2). The
// alias colours that failed AA move to darker steps: warning → amber.700,
// info → blue.700, error → red.600, success → brand.600.
const legacy = {
  "primary-light": resolve("brand.500"),
  ink: "#0f0f0f",
  "brand-accent": resolve("brand.500"),
  "brand-secondary": resolve("violet.600"),
  success: resolve("brand.600"),
  "success-light": resolve("brand.100"),
  "success-dark": resolve("brand.800"),
  error: resolve("red.600"),
  "error-light": resolve("red.100"),
  "error-dark": resolve("red.800"),
  warning: resolve("amber.700"),
  "warning-light": resolve("amber.100"),
  "warning-dark": resolve("amber.800"),
  info: resolve("blue.700"),
  "info-light": resolve("blue.100"),
  "info-dark": resolve("blue.800"),
  "surface-muted": resolve("slate.50"),
  "surface-subtle": resolve("slate.100"),
  background: "#ffffff",
  foreground: "#000000",
};
const legacyMixes = {
  "primary-soft": "color-mix(in srgb, var(--rs-primary) 8%, transparent)",
  "brand-accent-soft": "color-mix(in srgb, var(--rs-brand-accent) 12%, transparent)",
  "brand-secondary-soft":
    "color-mix(in srgb, var(--rs-brand-secondary) 12%, transparent)",
};

// Tailwind palette names used by pages not yet migrated, mapped onto the token
// ramps so every colour on screen comes from tokens.css (R1.4).
const PALETTE_ALIASES = {
  green: "brand",
  emerald: "brand",
  teal: "brand",
  yellow: "amber",
  purple: "violet",
  indigo: "violet",
  rose: "pink",
  sky: "cyan",
  gray: "slate",
  zinc: "slate",
  neutral: "stone",
};
const STEPS = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];

/** CSS value for `<hue>-<step>`; missing steps are mixed from neighbours. */
function rampStepCss(hue, step) {
  const ramp = tokens.color[hue];
  if (ramp[step]) return `var(--rs-${hue}-${step})`;
  const mix = (a, b, pct = 50) =>
    `color-mix(in srgb, var(--rs-${hue}-${a}) ${pct}%, var(--rs-${hue}-${b}))`;
  switch (step) {
    case "200":
      return mix("100", "300");
    case "400":
      return mix("300", "500");
    case "900":
      return `color-mix(in srgb, var(--rs-${hue}-800) 80%, #000)`;
    case "950":
      return `color-mix(in srgb, var(--rs-${hue}-800) 60%, #000)`;
    default:
      throw new Error(`No rule for ${hue}-${step}`);
  }
}

// ── web: tokens.css ──────────────────────────────────────────────────────
function buildCss() {
  const root = [];
  const theme = [];
  for (const [hue, ramp] of Object.entries(tokens.color)) {
    for (const [step, hex] of Object.entries(ramp)) {
      root.push(`  --rs-${hue}-${step}: ${hex.toLowerCase()};`);
    }
  }
  for (const [k, v] of Object.entries(semantic)) root.push(`  --rs-${k}: ${v};`);
  for (const [k, v] of Object.entries(legacy)) root.push(`  --rs-${k}: ${v};`);
  for (const [k, v] of Object.entries(legacyMixes)) root.push(`  --rs-${k}: ${v};`);
  for (const [name, s] of Object.entries(status)) {
    for (const role of Object.keys(tokens.statusRoles)) {
      root.push(`  --rs-status-${kebab(name)}-${role}: ${s[role]};`);
    }
  }
  for (const [code, p] of Object.entries(products)) {
    const id = code === "_unknown" ? "unknown" : kebab(code);
    for (const role of ["bg", "fg", "border"]) {
      root.push(`  --rs-product-${id}-${role}: ${p[role]};`);
    }
  }
  identity.forEach((c, i) => root.push(`  --rs-identity-${i}: ${c.hex};`));
  chart.forEach((c, i) => root.push(`  --rs-chart-${i}: ${c};`));
  for (const [k, v] of Object.entries(tokens.chrome)) {
    root.push(`  --rs-chrome-${kebab(k)}: ${v}px;`);
  }
  for (const [d, v] of Object.entries(tokens.density)) {
    root.push(`  --rs-density-${d}-row: ${v.row}px;`);
    root.push(`  --rs-density-${d}-input: ${v.input}px;`);
  }

  // Tailwind @theme map: ramps, aliases, semantic, status, product.
  const colorVars = [];
  for (const hue of Object.keys(tokens.color)) {
    for (const step of STEPS) {
      colorVars.push([`${hue}-${step}`, rampStepCss(hue, step)]);
    }
  }
  for (const [alias, hue] of Object.entries(PALETTE_ALIASES)) {
    for (const step of STEPS) {
      colorVars.push([`${alias}-${step}`, rampStepCss(hue, step)]);
    }
  }
  for (const k of [...Object.keys(semantic), ...Object.keys(legacy), ...Object.keys(legacyMixes)]) {
    colorVars.push([k, `var(--rs-${k})`]);
  }
  colorVars.push(["white", "#ffffff"], ["black", "var(--rs-ink)"]);
  for (const name of Object.keys(status)) {
    for (const role of Object.keys(tokens.statusRoles)) {
      colorVars.push([`status-${kebab(name)}-${role}`, `var(--rs-status-${kebab(name)}-${role})`]);
    }
  }
  for (const code of Object.keys(products)) {
    const id = code === "_unknown" ? "unknown" : kebab(code);
    for (const role of ["bg", "fg", "border"]) {
      colorVars.push([`product-${id}-${role}`, `var(--rs-product-${id}-${role})`]);
    }
  }
  identity.forEach((_, i) => colorVars.push([`identity-${i}`, `var(--rs-identity-${i})`]));

  // Plain `--color-*` custom properties are also published on :root so inline
  // styles such as `var(--color-primary)` keep resolving.
  for (const [k, v] of colorVars) root.push(`  --color-${k}: ${v};`);
  for (const [k, v] of colorVars) theme.push(`  --color-${k}: ${v};`);
  // Radii are published as --rs-radius-* only. The Tailwind `rounded-*` scale
  // stays as globals.css defines it, so untouched pages keep their shape
  // (task 1.3: no visual change beyond the AA alias colours).
  for (const [k, v] of Object.entries(tokens.radius)) {
    root.push(`  --rs-radius-${k}: ${v}px;`);
  }

  return [
    `/* ${HEADER} */`,
    "",
    ":root {",
    ...root,
    "}",
    "",
    "@theme inline {",
    ...theme,
    "}",
    "",
  ].join("\n");
}

// ── web/driver: tokens.ts ────────────────────────────────────────────────
const lit = (v) => JSON.stringify(v, null, 2);
function buildTs() {
  const codes = Object.keys(products).filter((c) => c !== "_unknown");
  return [
    `// ${HEADER}`,
    "",
    `export const COLOR = ${lit(tokens.color)} as const;`,
    "",
    `export const SEMANTIC = ${lit(semantic)} as const;`,
    "",
    `export type StatusKey = ${Object.keys(status).map((s) => JSON.stringify(s)).join(" | ")};`,
    "",
    "export interface StatusToken {",
    "  hue: string;",
    "  icon: string;",
    "  label: string;",
    "  strike: boolean;",
    "  bg: string;",
    "  fg: string;",
    "  dot: string;",
    "  border: string;",
    "}",
    "",
    `export const STATUS: Record<StatusKey, StatusToken> = ${lit(status)};`,
    "",
    `export const STATUS_KEYS = ${lit(Object.keys(status))} as StatusKey[];`,
    "",
    `export type ProductCode = ${codes.map((c) => JSON.stringify(c)).join(" | ")};`,
    "",
    "export interface ProductToken {",
    "  name: string | null;",
    "  bg: string;",
    "  fg: string;",
    "  border: string;",
    "  symbol: string;",
    "}",
    "",
    `export const PRODUCT: Record<ProductCode | "_unknown", ProductToken> = ${lit(products)};`,
    "",
    `export const PRODUCT_CODES = ${lit(codes)} as ProductCode[];`,
    "",
    `export const IDENTITY = ${lit(identity)} as const;`,
    "",
    `export const IDENTITY_ADJACENCY_AVOID = ${lit(tokens.identityAdjacencyAvoid)} as const;`,
    "",
    `export const CHART = ${lit(chart)} as const;`,
    "",
    `export const CHROME = ${lit(tokens.chrome)} as const;`,
    "",
    `export const DENSITY = ${lit(tokens.density)} as const;`,
    "",
    `export const FONT = ${lit(tokens.font)} as const;`,
    "",
    `export const RADIUS = ${lit(tokens.radius)} as const;`,
    "",
    `export const SPACE = ${lit(tokens.space)} as const;`,
    "",
  ].join("\n");
}

function buildDriverTs() {
  return [
    buildTs().trimEnd(),
    "",
    `export const DRIVER = ${lit(tokens.driver)} as const;`,
    "",
  ].join("\n");
}

// ── driver: global.css block (HSL triplets for NativeWind) ───────────────
function hexToHsl(hex) {
  const n = Number.parseInt(hex.slice(1), 16);
  const r = ((n >> 16) & 255) / 255;
  const g = ((n >> 8) & 255) / 255;
  const b = (n & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = (g - b) / d + (g < b ? 6 : 0);
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
  }
  return `${Math.round(h)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}
function buildDriverBlock() {
  const n = tokens.driver.night;
  const light = {
    background: semantic.surface,
    foreground: semantic.text,
    card: semantic.surface,
    "card-foreground": semantic.text,
    popover: semantic.surface,
    "popover-foreground": semantic.text,
    primary: semantic.primary,
    "primary-foreground": semantic["on-primary"],
    secondary: resolve("slate.100"),
    "secondary-foreground": semantic.text,
    muted: resolve("slate.100"),
    "muted-foreground": semantic["text-muted"],
    accent: resolve("brand.50"),
    "accent-foreground": resolve("brand.800"),
    destructive: semantic.danger,
    "destructive-foreground": "#ffffff",
    border: semantic.border,
    input: semantic.border,
    ring: semantic.focus,
  };
  const dark = {
    background: n.canvas,
    foreground: n.text,
    card: n.surface,
    "card-foreground": n.text,
    popover: n.surface,
    "popover-foreground": n.text,
    primary: n.primary,
    "primary-foreground": n["on-primary"],
    secondary: n.border,
    "secondary-foreground": n.text,
    muted: n.border,
    "muted-foreground": n["text-muted"],
    accent: n.border,
    "accent-foreground": n.text,
    destructive: resolve("red.500"),
    "destructive-foreground": "#ffffff",
    border: n.border,
    input: n.border,
    ring: n.primary,
  };
  const vars = (o) => Object.entries(o).map(([k, v]) => `    --${k}: ${hexToHsl(v)};`);
  return [
    "/* tokens:start */",
    `/* ${HEADER} */`,
    "@layer base {",
    "  :root {",
    ...vars(light),
    "  }",
    "  .dark:root {",
    ...vars(dark),
    "  }",
    "}",
    "/* tokens:end */",
  ].join("\n");
}

function spliceDriverCss(current) {
  const start = current.indexOf("/* tokens:start */");
  const end = current.indexOf("/* tokens:end */");
  if (start < 0 || end < 0) {
    throw new Error("driver-app/global.css is missing the tokens:start/tokens:end markers");
  }
  return current.slice(0, start) + buildDriverBlock() + current.slice(end + "/* tokens:end */".length);
}

// ── write / check ────────────────────────────────────────────────────────
const outputs = [
  ["runsheet/src/styles/tokens.css", () => buildCss()],
  ["runsheet/src/styles/tokens.ts", () => buildTs()],
];
if (WITH_DRIVER) {
  outputs.push(["driver-app/lib/tokens.ts", () => buildDriverTs()]);
  outputs.push([
    "driver-app/global.css",
    () => spliceDriverCss(readFileSync(join(ROOT, "driver-app/global.css"), "utf8")),
  ]);
}

let stale = 0;
for (const [rel, build] of outputs) {
  const path = join(ROOT, rel);
  const next = build();
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (CHECK) {
    if (current !== next) {
      stale += 1;
      const cur = (current ?? "").split("\n");
      const nxt = next.split("\n");
      const line = nxt.findIndex((l, i) => l !== cur[i]);
      console.error(
        `✗ ${rel} is stale (first difference at line ${line + 1}; ${cur.length} vs ${nxt.length} lines)`,
      );
    }
  } else if (current !== next) {
    writeFileSync(path, next);
    console.log(`wrote ${relative(ROOT, path)}`);
  }
}
if (CHECK) {
  if (stale) {
    console.error(`${stale} generated file(s) differ. Run: node scripts/build-tokens.mjs`);
    process.exit(1);
  }
  console.log("✓ generated token files are up to date");
}
