"""
Property-based test for WebSocket session-credential log redaction.

# Feature: supertokens-auth-migration, Property 10: WebSocket credentials are never logged

**Validates: Requirements 7.4, 7.5**

Property 10: WebSocket credentials are never logged — for any WebSocket
handshake, no log record emitted while extracting the credential
(``_extract_session_credential``), resolving the session
(``_resolve_ws_claims`` via the ``configure_ws_session_verifier`` seam), or
authenticating the connection (``_authenticate_tenant`` /
``_authenticate_driver``) contains the credential (session-token) value.

This holds regardless of:

* where the credential is carried — the ``Authorization: Bearer`` handshake
  header, the ``sAccessToken`` cookie on the handshake, or the short-lived
  ``token`` query parameter fallback (Req 7.5);
* the active ``auth_provider`` (``supertokens`` / ``dual`` / ``legacy``);
* whether verification succeeds, returns no session, or raises (so the
  failure-logging branch in the default SDK verifier is exercised) (Req 7.4).

How the property is exercised
-----------------------------
A root-level logging handler captures **every** fully-formatted log record
(``record.getMessage()`` so ``%s`` args are interpolated) emitted on any logger
during the auth call. We then assert the randomly generated credential value
never appears in the captured text. Because the credential is generated by
Hypothesis and threaded through the cookie / query param, any code path that
logged it — directly or via a ``%s`` argument — would surface it in the capture
and fail the property.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import contextmanager
from unittest.mock import MagicMock, patch

from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

import bootstrap.websockets as ws


# ---------------------------------------------------------------------------
# Log capture: collect every formatted record emitted on any logger
# ---------------------------------------------------------------------------
class _CapturingHandler(logging.Handler):
    """Records the fully-formatted message of every log record it sees."""

    def __init__(self) -> None:
        super().__init__(level=logging.DEBUG)
        self.messages: list[str] = []

    def emit(self, record: logging.LogRecord) -> None:  # noqa: D401
        try:
            # getMessage() interpolates %s/%d args, so a credential passed as a
            # logging argument (not just inline) is still surfaced here.
            self.messages.append(record.getMessage())
        except Exception:  # noqa: BLE001 - never let logging break the test
            self.messages.append(repr(record.msg))

    @property
    def text(self) -> str:
        return "\n".join(self.messages)


@contextmanager
def _capture_all_logs():
    """Attach a DEBUG handler to the root logger and force the WS-relevant
    loggers to DEBUG so no record is filtered out before capture."""
    handler = _CapturingHandler()
    root = logging.getLogger()
    affected = [root, logging.getLogger("main"), logging.getLogger("bootstrap.websockets")]
    prev_levels = [lg.level for lg in affected]
    root.addHandler(handler)
    for lg in affected:
        lg.setLevel(logging.DEBUG)
    try:
        yield handler
    finally:
        root.removeHandler(handler)
        for lg, lvl in zip(affected, prev_levels):
            lg.setLevel(lvl)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _make_settings(auth_provider="supertokens"):
    settings_obj = MagicMock()
    settings_obj.auth_provider = auth_provider
    return settings_obj


def _make_ws(token: str, transport: str):
    """Build a fake WebSocket carrying ``token`` via header, cookie, or query."""
    websocket = MagicMock()
    if transport == "header":
        websocket.query_params = {}
        websocket.headers = {"authorization": f"Bearer {token}"}
    elif transport == "cookie":
        websocket.query_params = {}
        websocket.headers = {"cookie": f"foo=bar; sAccessToken={token}; baz=qux"}
    else:  # "query"
        websocket.query_params = {"token": token}
        websocket.headers = {}
    return websocket


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------
# Credential values: non-trivial, URL/cookie-safe-ish token strings. We avoid
# ';' and '=' so the cookie parser keeps the value intact, and require a
# minimum length so an empty/coincidental substring can't match.
_tokens = st.text(
    alphabet=st.characters(
        whitelist_categories=("Ll", "Lu", "Nd"),
        whitelist_characters="-_.",
    ),
    min_size=8,
    max_size=64,
)
_transports = st.sampled_from(["header", "cookie", "query"])
_providers = st.sampled_from(["supertokens"])
_verify_behaviors = st.sampled_from(["valid", "none", "raise_default"])


# ---------------------------------------------------------------------------
# Property 10 — the session credential is never written to logs
# ---------------------------------------------------------------------------
# Feature: supertokens-auth-migration, Property 10: WebSocket credentials are never logged
class TestWebSocketCredentialRedaction:
    """**Validates: Requirements 7.4, 7.5**"""

    def teardown_method(self, method):
        # Reset the verifier seam so nothing leaks into other tests.
        ws.configure_ws_session_verifier(None)

    @given(
        token=_tokens,
        transport=_transports,
        provider=_providers,
        behavior=_verify_behaviors,
        authenticator=st.sampled_from(["tenant", "driver"]),
    )
    @settings(
        max_examples=100,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
    )
    def test_credential_never_appears_in_logs(
        self,
        token: str,
        transport: str,
        provider: str,
        behavior: str,
        authenticator: str,
    ):
        """No log record emitted during credential extraction / session
        resolution / authentication contains the credential value."""
        # First confirm the credential is actually present on the handshake so
        # the test is meaningful (i.e. there *is* a secret that could leak).
        probe_ws = _make_ws(token, transport)
        extracted, _anti_csrf = ws._extract_session_credential(probe_ws)
        assume(extracted == token)

        websocket = _make_ws(token, transport)

        if behavior == "valid":
            async def fake_verify(access_token, anti_csrf):
                # A complete session: tenant_id (+ driver_id) present.
                return {"tenant_id": "t-1", "driver_id": "d-1", "roles": ["admin"]}

            ws.configure_ws_session_verifier(fake_verify)
            sdk_patch = patch.dict({}, {})  # no-op context manager
        elif behavior == "none":
            async def fake_verify(access_token, anti_csrf):
                return None

            ws.configure_ws_session_verifier(fake_verify)
            sdk_patch = patch.dict({}, {})  # no-op context manager
        else:  # "raise_default": use the default SDK verifier and make it raise
            ws.configure_ws_session_verifier(None)
            sdk_patch = patch(
                "supertokens_python.recipe.session.asyncio."
                "get_session_without_request_response",
                side_effect=RuntimeError("verification failed"),
            )

        async def _run():
            if authenticator == "tenant":
                return await ws._authenticate_tenant(websocket)
            return await ws._authenticate_driver(websocket)

        with _capture_all_logs() as logs:
            with patch("config.settings.get_settings",
                       return_value=_make_settings(provider)):
                with sdk_patch:
                    asyncio.run(_run())

        # The credential value must never be written to any log record
        # (Req 7.4, 7.5).
        assert token not in logs.text, (
            f"credential leaked into logs for transport={transport!r} "
            f"provider={provider!r} behavior={behavior!r} "
            f"authenticator={authenticator!r}:\n{logs.text}"
        )
