"""
Tenant Credentials Vault — KMS envelope encryption for third-party secrets.

Implements the per-tenant secret store required by the Integration Layer (Capability
5). Credentials are encrypted at rest using AWS KMS envelope encryption:

    1. A random 256-bit Data Encryption Key (DEK) is generated by KMS via
       ``GenerateDataKey`` and returned to us as both plaintext and a
       KMS-wrapped ``CiphertextBlob``.
    2. The plaintext DEK is used to AES-GCM-encrypt the caller-supplied
       ``plaintext`` payload. Nonce (12 bytes) is prepended to the
       ciphertext+tag output so we can round-trip with a single binary blob.
    3. Only the wrapped DEK and the AES-GCM output are persisted to the
       ``tenant_credentials`` ES index; the plaintext DEK is discarded.
    4. Decryption reverses these steps: KMS.Decrypt unwraps the DEK, then
       AES-GCM decrypts the ciphertext.

Every read or write requires a ``tenant_id`` argument and verifies it against the
persisted document's ``tenant_id`` — cross-tenant ref access raises ``PermissionError``
(Requirement 5.1.3).

Validates: Requirement 5.1 (Pluggable Integration Framework — credentials vault),
Requirement 10.1 (tenant isolation on all vault reads/writes).
"""
from __future__ import annotations

import base64
import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from fuel.services.fuel_ops_es_mappings import TENANT_CREDENTIALS_INDEX

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Algorithm identifier stored alongside each record for forward-compatibility.
ALGORITHM = "AES_256_GCM_KMS_ENVELOPE_V1"

#: AES-GCM standard nonce length in bytes.
_NONCE_BYTES = 12

#: KMS data-key spec matching ``AES_256_GCM_KMS_ENVELOPE_V1``.
_KMS_KEY_SPEC = "AES_256"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _utcnow_iso() -> str:
    """Return a timezone-aware UTC timestamp in ISO-8601 form."""
    return datetime.now(timezone.utc).isoformat()


def aes_gcm_encrypt(key: bytes, plaintext: bytes, associated_data: Optional[bytes] = None) -> bytes:
    """AES-256-GCM encrypt ``plaintext`` under ``key``.

    Returns ``nonce || ciphertext_with_tag`` as a single ``bytes`` blob so the
    output can be persisted as one binary field. Callers MUST supply a 32-byte
    key — the plaintext DEK returned by ``kms.generate_data_key``.

    Args:
        key: 32-byte symmetric key (the AES-256 DEK).
        plaintext: Payload bytes to encrypt.
        associated_data: Optional additional authenticated data bound into the
            GCM tag; pass the same value on decrypt.

    Returns:
        ``nonce || ciphertext || tag`` as a single ``bytes`` object.
    """
    if len(key) != 32:
        raise ValueError("AES-256 key must be 32 bytes")
    aesgcm = AESGCM(key)
    nonce = os.urandom(_NONCE_BYTES)
    ct = aesgcm.encrypt(nonce, plaintext, associated_data)
    return nonce + ct


def aes_gcm_decrypt(key: bytes, blob: bytes, associated_data: Optional[bytes] = None) -> bytes:
    """Reverse of :func:`aes_gcm_encrypt`. Raises ``InvalidTag`` on tamper."""
    if len(key) != 32:
        raise ValueError("AES-256 key must be 32 bytes")
    if len(blob) <= _NONCE_BYTES:
        raise ValueError("ciphertext blob too short")
    nonce, ct = blob[:_NONCE_BYTES], blob[_NONCE_BYTES:]
    return AESGCM(key).decrypt(nonce, ct, associated_data)


# ---------------------------------------------------------------------------
# Vault
# ---------------------------------------------------------------------------


class TenantCredentialsVault:
    """Per-tenant encrypted credential store backed by AWS KMS + Elasticsearch.

    The vault is tenant-scoped: every read and write takes a ``tenant_id`` and
    refuses to operate on a ref whose persisted ``tenant_id`` does not match
    (``PermissionError``).

    Args:
        es_service: An ``ElasticsearchService``-compatible instance exposing
            ``index_document``, ``get_document``, ``update_document``,
            ``delete_document``, and ``search_documents`` coroutines.
        kms_key_id: Default KMS CMK ID used when callers of ``put`` do not
            specify one explicitly. May be ``None`` if callers always override.
        kms_client: Optional pre-built boto3 KMS client. When omitted a client
            is lazily constructed with ``boto3.client("kms")`` — tests inject a
            mock here so no AWS calls are made.
    """

    INDEX = TENANT_CREDENTIALS_INDEX

    def __init__(
        self,
        es_service,
        kms_key_id: Optional[str] = None,
        kms_client: Any = None,
    ) -> None:
        self._es = es_service
        self._default_key_id = kms_key_id
        self._kms_client = kms_client

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def put(
        self,
        tenant_id: str,
        key: str,
        plaintext: Dict[str, Any],
        kms_key_id: Optional[str] = None,
        provider_name: Optional[str] = None,
    ) -> str:
        """Encrypt and persist ``plaintext`` for ``tenant_id`` under ``key``.

        Generates a fresh DEK from KMS, AES-GCM-encrypts the JSON-serialized
        payload, and writes the resulting ciphertext + wrapped DEK to the
        ``tenant_credentials`` index. Returns an opaque ``ref`` string that
        callers store in ``integration_instances.credentials_ref``.

        Args:
            tenant_id: Owning tenant. Non-empty.
            key: Logical credential name (e.g. ``"qbo_oauth"``); one credential
                may exist per (tenant, key).
            plaintext: JSON-serializable credential payload.
            kms_key_id: Optional override of the default CMK.
            provider_name: Optional tag recording which integration provider
                owns this credential (surfaced to admins as metadata).

        Returns:
            The ``ref`` string of the persisted credential.

        Raises:
            ValueError: If ``tenant_id`` or ``key`` is empty, or no KMS key is
                configured.
        """
        self._require_tenant(tenant_id)
        if not key:
            raise ValueError("credential key must be non-empty")

        effective_key_id = kms_key_id or self._default_key_id
        if not effective_key_id:
            raise ValueError(
                "kms_key_id required: pass one explicitly or set a default on the vault"
            )

        wrapped_dek_bytes, ciphertext_bytes = self._encrypt_payload(
            plaintext, effective_key_id, tenant_id, key
        )

        ref = self._build_ref(tenant_id, key)
        now = _utcnow_iso()
        doc = {
            "ref": ref,
            "tenant_id": tenant_id,
            "key": key,
            "provider_name": provider_name,
            "wrapped_dek": base64.b64encode(wrapped_dek_bytes).decode("ascii"),
            "ciphertext": base64.b64encode(ciphertext_bytes).decode("ascii"),
            "kms_key_id": effective_key_id,
            "algorithm": ALGORITHM,
            "rotated_at": None,
            "created_at": now,
            "updated_at": now,
        }
        await self._es.index_document(self.INDEX, ref, doc)
        logger.info(
            "Stored credential ref=%s tenant_id=%s key=%s provider=%s",
            ref,
            tenant_id,
            key,
            provider_name,
        )
        return ref

    async def get(self, tenant_id: str, ref: str) -> Dict[str, Any]:
        """Decrypt and return the plaintext credential identified by ``ref``.

        Raises:
            PermissionError: If ``ref`` belongs to a different tenant.
            KeyError: If ``ref`` does not exist.
        """
        self._require_tenant(tenant_id)
        if not ref:
            raise ValueError("ref must be non-empty")

        doc = await self._load_doc(ref)
        self._assert_tenant_match(doc, tenant_id, ref)

        plaintext_bytes = self._decrypt_doc(doc, tenant_id)
        return json.loads(plaintext_bytes.decode("utf-8"))

    async def rotate(
        self,
        tenant_id: str,
        ref: str,
        kms_key_id: Optional[str] = None,
    ) -> str:
        """Re-wrap the credential under a fresh DEK (and optionally a new CMK).

        The plaintext is unchanged; only the wrapped DEK and ciphertext are
        regenerated. Returns the unchanged ``ref`` so integration instances do
        not need to update their ``credentials_ref``.

        Raises:
            PermissionError: If ``ref`` belongs to a different tenant.
            KeyError: If ``ref`` does not exist.
        """
        self._require_tenant(tenant_id)
        if not ref:
            raise ValueError("ref must be non-empty")

        doc = await self._load_doc(ref)
        self._assert_tenant_match(doc, tenant_id, ref)

        plaintext_bytes = self._decrypt_doc(doc, tenant_id)
        payload = json.loads(plaintext_bytes.decode("utf-8"))

        effective_key_id = kms_key_id or doc.get("kms_key_id") or self._default_key_id
        if not effective_key_id:
            raise ValueError("rotate requires a kms_key_id on the existing record or caller")

        wrapped_dek_bytes, ciphertext_bytes = self._encrypt_payload(
            payload, effective_key_id, tenant_id, doc.get("key", "")
        )

        update = {
            "wrapped_dek": base64.b64encode(wrapped_dek_bytes).decode("ascii"),
            "ciphertext": base64.b64encode(ciphertext_bytes).decode("ascii"),
            "kms_key_id": effective_key_id,
            "algorithm": ALGORITHM,
            "rotated_at": _utcnow_iso(),
        }
        await self._es.update_document(self.INDEX, ref, update)
        logger.info("Rotated credential ref=%s tenant_id=%s", ref, tenant_id)
        return ref

    async def delete(self, tenant_id: str, ref: str) -> bool:
        """Delete a credential after verifying tenant ownership.

        Returns ``True`` if the credential was deleted, ``False`` if it did not
        exist. Raises ``PermissionError`` if ``ref`` belongs to another tenant.
        """
        self._require_tenant(tenant_id)
        if not ref:
            raise ValueError("ref must be non-empty")

        try:
            doc = await self._load_doc(ref)
        except KeyError:
            return False
        self._assert_tenant_match(doc, tenant_id, ref)
        return bool(await self._es.delete_document(self.INDEX, ref))

    async def list_for_tenant(
        self,
        tenant_id: str,
        provider_name: Optional[str] = None,
        size: int = 100,
    ) -> List[Dict[str, Any]]:
        """Return credential metadata (no secret material) for ``tenant_id``.

        The returned dicts intentionally exclude ``wrapped_dek`` and
        ``ciphertext`` so they are safe to surface to admin UIs. Callers must
        round-trip through :meth:`get` to retrieve the plaintext.

        Args:
            tenant_id: Owning tenant.
            provider_name: Optional filter on provider tag.
            size: Maximum number of records to return.
        """
        self._require_tenant(tenant_id)

        filters: List[Dict[str, Any]] = [{"term": {"tenant_id": tenant_id}}]
        if provider_name:
            filters.append({"term": {"provider_name": provider_name}})

        query = {
            "query": {"bool": {"filter": filters}},
            "sort": [{"created_at": {"order": "desc"}}],
            "size": size,
        }

        response = await self._es.search_documents(self.INDEX, query, size=size)
        hits = (response or {}).get("hits", {}).get("hits", []) or []
        return [self._redact(hit.get("_source") or {}) for hit in hits]

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @staticmethod
    def _require_tenant(tenant_id: str) -> None:
        if not tenant_id:
            raise ValueError("tenant_id must be non-empty")

    @staticmethod
    def _build_ref(tenant_id: str, key: str) -> str:
        """Generate a globally-unique credential ref including tenant + key.

        Format: ``cred:{tenant_id}:{key}:{uuid4}``.
        """
        return f"cred:{tenant_id}:{key}:{uuid.uuid4()}"

    @staticmethod
    def _assert_tenant_match(doc: Dict[str, Any], tenant_id: str, ref: str) -> None:
        doc_tenant = doc.get("tenant_id")
        if doc_tenant != tenant_id:
            # Do NOT leak the real owner in the exception message.
            logger.warning(
                "Cross-tenant vault access denied: ref=%s requester=%s owner=%s",
                ref,
                tenant_id,
                doc_tenant,
            )
            raise PermissionError("cross_tenant_credential_access_denied")

    async def _load_doc(self, ref: str) -> Dict[str, Any]:
        """Fetch the raw credential document or raise ``KeyError``."""
        try:
            doc = await self._es.get_document(self.INDEX, ref)
        except Exception as exc:  # elasticsearch NotFoundError, AppException, etc.
            status = getattr(exc, "status_code", None)
            if status == 404 or "not_found" in str(exc).lower():
                raise KeyError(ref) from exc
            raise
        if doc is None:
            raise KeyError(ref)
        # ``get_document`` returns the ``_source`` body directly; if a mock ever
        # hands back the envelope instead we unwrap gracefully.
        if isinstance(doc, dict) and "_source" in doc and "tenant_id" not in doc:
            doc = doc["_source"]
        return doc

    def _kms(self):
        """Lazily construct a boto3 KMS client on first use."""
        if self._kms_client is not None:
            return self._kms_client
        import boto3  # imported lazily so unit tests without AWS config still import this module
        self._kms_client = boto3.client("kms")
        return self._kms_client

    def _encrypt_payload(
        self,
        plaintext: Dict[str, Any],
        kms_key_id: str,
        tenant_id: str,
        key: str,
    ) -> tuple[bytes, bytes]:
        """Return ``(wrapped_dek, ciphertext_blob)`` for the supplied payload."""
        encryption_context = {"tenant_id": tenant_id, "key": key}
        dek = self._kms().generate_data_key(
            KeyId=kms_key_id,
            KeySpec=_KMS_KEY_SPEC,
            EncryptionContext=encryption_context,
        )
        plaintext_key = dek["Plaintext"]
        wrapped_dek = dek["CiphertextBlob"]
        try:
            serialized = json.dumps(plaintext, sort_keys=True).encode("utf-8")
            ciphertext = aes_gcm_encrypt(plaintext_key, serialized)
        finally:
            # Best-effort scrub of the plaintext DEK.
            plaintext_key = b"\x00" * len(plaintext_key)  # noqa: F841
        return wrapped_dek, ciphertext

    def _decrypt_doc(self, doc: Dict[str, Any], tenant_id: str) -> bytes:
        """Unwrap the DEK via KMS and AES-GCM-decrypt the payload."""
        try:
            wrapped = base64.b64decode(doc["wrapped_dek"])
            ciphertext = base64.b64decode(doc["ciphertext"])
        except (KeyError, ValueError) as exc:
            raise ValueError(f"credential document is corrupt: {exc}") from exc

        encryption_context = {"tenant_id": tenant_id, "key": doc.get("key", "")}
        decrypted = self._kms().decrypt(
            CiphertextBlob=wrapped,
            EncryptionContext=encryption_context,
        )
        plaintext_key = decrypted["Plaintext"]
        try:
            return aes_gcm_decrypt(plaintext_key, ciphertext)
        finally:
            plaintext_key = b"\x00" * len(plaintext_key)  # noqa: F841

    @staticmethod
    def _redact(source: Dict[str, Any]) -> Dict[str, Any]:
        """Return a shallow copy with cipher material removed."""
        redacted = dict(source)
        redacted.pop("wrapped_dek", None)
        redacted.pop("ciphertext", None)
        return redacted
